# Revisión de divisas con suficiente antiguedad

In [3]:
import os
os.chdir("C:/TFM/tfm_env/")

In [44]:
import pandas as pd

dir = "data/01_raw/DatosHistoricosPrecios/ParDivisas/"

for file in os.listdir(dir):

    df = pd.read_csv(dir + file, header=[0, 1], index_col=0, parse_dates=[0] )
    print(f"La fecha mínima para el par {file[:-6]} es {df.index.min()}")

La fecha mínima para el par AEDEUR es 2004-10-29 00:00:00
La fecha mínima para el par AUDEUR es 2003-12-01 00:00:00
La fecha mínima para el par BRLEUR es 2007-05-29 00:00:00
La fecha mínima para el par CADEUR es 2005-03-16 00:00:00
La fecha mínima para el par CHFEUR es 2005-03-16 00:00:00
La fecha mínima para el par CLPEUR es 2025-08-08 00:00:00
La fecha mínima para el par CNYEUR es 2003-12-01 00:00:00
La fecha mínima para el par DKKEUR es 2008-10-16 00:00:00
La fecha mínima para el par GBPEUR es 2003-09-17 00:00:00
La fecha mínima para el par HKDEUR es 2005-04-06 00:00:00
La fecha mínima para el par IDREUR es 2003-12-01 00:00:00
La fecha mínima para el par INREUR es 2004-10-25 00:00:00
La fecha mínima para el par JPYEUR es 2005-09-16 00:00:00
La fecha mínima para el par KRWEUR es 2003-12-01 00:00:00
La fecha mínima para el par MXNEUR es 2003-12-01 00:00:00
La fecha mínima para el par MYREUR es 2007-07-05 00:00:00
La fecha mínima para el par PLNEUR es 2004-10-29 00:00:00
La fecha mínima para el par SEKEUR es 2008-10-16 00:00:00
La fecha mínima para el par SGDEUR es 2006-02-16 00:00:00
La fecha mínima para el par TRYEUR es 2025-08-08 00:00:00
La fecha mínima para el par TWDEUR es 2025-08-08 00:00:00
La fecha mínima para el par USDEUR es 2003-12-01 00:00:00
La fecha mínima para el par ZAREUR es 2003-12-01 00:00:00

In [45]:
currencies_enough_old = os.listdir(dir)
currencies_enough_old.remove("CLPEUR=X.csv")
currencies_enough_old.remove("TRYEUR=X.csv")
currencies_enough_old.remove("TWDEUR=X.csv")

In [49]:
currency_value_df = pd.read_csv(dir + "AEDEUR=X.csv", header=[0, 1], index_col=0, parse_dates=[0] )

In [129]:
df = pd.read_excel("data/01_raw/MuestraEstadosFinancieros/ConsumoDiscrecional/AUD - BRG - Financials (30.6.04 - 30.6.24)1.xlsx")

In [130]:
df

,Income Statement | TIKR.com,30/6/04,30/6/05,30/6/07,30/6/08,30/6/09,30/6/10,30/6/11,30/6/12,30/6/13,...,30/6/16,30/6/17,30/6/18,30/6/19,30/6/20,30/6/21,30/6/22,30/6/23,30/6/24,LTM
0,Total Revenues,457.616000,441.047000,371.279,425.561000,431.941000,420.889000,393.589000,408.476000,469.476000,...,576.127000,605.599000,652.348000,759.967000,952.244000,1187.659000,1418.437000,1478.554000,1529.993000,1621.679
1,% Change YoY,0.003583,-0.036207,NaN,0.146203,0.014992,-0.025587,-0.064863,0.037824,0.149336,...,0.094206,0.051155,0.077195,0.164972,0.253007,0.247221,0.194313,0.042383,0.034790,NaN
2,Cost of Goods Sold,-270.853000,-255.312000,-237.728,-280.755000,-280.636000,-260.341000,-227.841000,-237.016000,-291.930000,...,-385.525000,-409.057000,-420.088000,-488.767000,-631.684000,-773.991000,-932.500000,-961.612000,-973.055000,-1030.512
3,Gross Profit,186.763000,185.735000,133.551,144.806000,151.305000,160.548000,165.748000,171.460000,177.546000,...,190.602000,196.542000,232.260000,271.200000,320.560000,413.668000,485.937000,516.942000,556.938000,591.167
4,% Change YoY,0.072568,-0.005504,NaN,0.084275,0.044881,0.061089,0.032389,0.034462,0.035495,...,0.104568,0.031164,0.181732,0.167657,0.182006,0.290454,0.174703,0.063805,0.077370,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Additional Metrics:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Total Interest Income,0.411000,0.368000,0.337,0.648000,0.329000,0.154000,0.582000,0.984000,1.328000,...,0.336000,0.624000,1.044000,0.449000,0.192000,0.130000,0.317000,0.669000,2.431000,2.442
66,Interest Expense,5.369000,6.275000,5.089,5.972000,5.936000,4.472000,2.705000,1.998000,1.656000,...,2.549000,2.421000,3.580000,3.483000,6.780000,7.943000,7.265000,17.559000,17.927000,13.530
67,Net Interest Income,-4.959000,-5.907000,-4.752,-5.324000,-5.607000,-4.318000,-2.123000,-1.014000,-0.328000,...,-2.213000,-1.797000,-2.536000,-3.034000,-8.176000,-9.027000,-8.527000,-21.030000,-20.026000,-15.601
68,% Change YoY,0.014525,0.191168,NaN,0.120370,0.053156,0.229891,0.508337,0.522374,0.676529,...,0.204682,0.187980,0.411241,0.196372,1.694792,0.104085,0.055389,1.466284,0.047741,NaN

In [126]:
from openpyxl import load_workbook
import pandas as pd

path = financial_statements_dir + "AUD - BRG - Financials (30.6.04 - 30.6.24).xlsx"
wb = load_workbook(path, data_only=True, read_only=True)
ws = wb["Income Statement"]  # o el nombre/índice que toque

# rows = ([(None if v=='NaN' else str(v)) for v in row] for row in ws.iter_rows(values_only=True))

# df = pd.DataFrame()
# for row in rows:
#     repaired_row=[]
#     for cell in row:
#         if "NaN" in cell:
#             repaired_row.append(cell.replace("NaN", ""))
#         else:
#             repaired_row.append(cell)
            
#     df = pd.concat([df, pd.DataFrame(repaired_row)])

first_line=True
d={}
for row in ws.iter_rows(values_only=True):
    
    if first_line:
        for cell in row:
            d[cell]=[]
        first_line=False
        
    else:
        for position, key in enumerate(d.keys()):
            d[key].append(row[position])

ValueError: invalid literal for int() with base 10: 'NaN'

In [124]:

for k in d.keys():
    print(k)

Income Statement | TIKR.com
30/6/04
30/6/05
30/6/07
30/6/08
30/6/09
30/6/10
30/6/11
30/6/12
30/6/13
30/6/14
30/6/15
30/6/16
30/6/17
30/6/18
30/6/19
30/6/20
30/6/21
30/6/22
30/6/23
30/6/24
LTM

In [ ]:
import yfinance as yf
data = yf.download("GOOGL", period='max')

C:\Users\Edelmín\AppData\Local\Temp\ipykernel_58116\2988577952.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download("GOOGL", period='max')
[*********************100%***********************]  1 of 1 completed

In [1]:
import os 
import pandas as pd
os.chdir("C:/TFM/tfm_env/")

In [7]:
data_path = "data/02_intermediate/01 - Corregido - EstadosFinancieros/ConsumoDiscrecional/AUD - BRG - Financials (30.6.04 - 30.6.24).xlsx"
df = pd.read_excel(data_path)

ValueError: invalid literal for int() with base 10: 'NaN'

In [5]:
df

,Income Statement | TIKR.com,30/6/04,30/6/05,30/6/07,30/6/08,30/6/09,30/6/10,30/6/11,30/6/12,30/6/13,...,30/6/16,30/6/17,30/6/18,30/6/19,30/6/20,30/6/21,30/6/22,30/6/23,30/6/24,LTM
0,Total Revenues,457.616000,441.047000,371.279,425.561000,431.941000,420.889000,393.589000,408.476000,469.476000,...,576.127000,605.599000,652.348000,759.967000,952.244000,1187.659000,1418.437000,1478.554000,1529.993000,1621.679
1,% Change YoY,0.003583,-0.036207,NaN,0.146203,0.014992,-0.025587,-0.064863,0.037824,0.149336,...,0.094206,0.051155,0.077195,0.164972,0.253007,0.247221,0.194313,0.042383,0.034790,NaN
2,Cost of Goods Sold,-270.853000,-255.312000,-237.728,-280.755000,-280.636000,-260.341000,-227.841000,-237.016000,-291.930000,...,-385.525000,-409.057000,-420.088000,-488.767000,-631.684000,-773.991000,-932.500000,-961.612000,-973.055000,-1030.512
3,Gross Profit,186.763000,185.735000,133.551,144.806000,151.305000,160.548000,165.748000,171.460000,177.546000,...,190.602000,196.542000,232.260000,271.200000,320.560000,413.668000,485.937000,516.942000,556.938000,591.167
4,% Change YoY,0.072568,-0.005504,NaN,0.084275,0.044881,0.061089,0.032389,0.034462,0.035495,...,0.104568,0.031164,0.181732,0.167657,0.182006,0.290454,0.174703,0.063805,0.077370,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Additional Metrics:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,Total Interest Income,0.411000,0.368000,0.337,0.648000,0.329000,0.154000,0.582000,0.984000,1.328000,...,0.336000,0.624000,1.044000,0.449000,0.192000,0.130000,0.317000,0.669000,2.431000,2.442
66,Interest Expense,5.369000,6.275000,5.089,5.972000,5.936000,4.472000,2.705000,1.998000,1.656000,...,2.549000,2.421000,3.580000,3.483000,6.780000,7.943000,7.265000,17.559000,17.927000,13.530
67,Net Interest Income,-4.959000,-5.907000,-4.752,-5.324000,-5.607000,-4.318000,-2.123000,-1.014000,-0.328000,...,-2.213000,-1.797000,-2.536000,-3.034000,-8.176000,-9.027000,-8.527000,-21.030000,-20.026000,-15.601
68,% Change YoY,0.014525,0.191168,NaN,0.120370,0.053156,0.229891,0.508337,0.522374,0.676529,...,0.204682,0.187980,0.411241,0.196372,1.694792,0.104085,0.055389,1.466284,0.047741,NaN

In [6]:
pip install polars

Collecting polars
  Downloading polars-1.32.3-cp39-abi3-win_amd64.whl.metadata (15 kB)
Downloading polars-1.32.3-cp39-abi3-win_amd64.whl (38.0 MB)
   ---------------------------------------- 0.0/38.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.0 MB ? eta -:--:--
    --------------------------------------- 0.8/38.0 MB 2.4 MB/s eta 0:00:16
   - -------------------------------------- 1.3/38.0 MB 2.3 MB/s eta 0:00:16
   - -------------------------------------- 1.8/38.0 MB 2.3 MB/s eta 0:00:16
   -- ------------------------------------- 2.4/38.0 MB 2.4 MB/s eta 0:00:16
   --- ------------------------------------ 2.9/38.0 MB 2.4 MB/s eta 0:00:15
   --- ------------------------------------ 3.4/38.0 MB 2.4 MB/s eta 0:00:15
   ---- ----------------------------------- 3.9/38.0 MB 2.4 MB/s eta 0:00:15
   ---- ----------------------------------- 4.5/38.0 MB 2.4 MB/s eta 0:00:15
   ---- ----------------------------------- 4.7/38.0 MB 2.4 MB/s eta 0:00:15
   ----- ---------------------------------- 5.2/38.0 MB 2.4 MB/s eta 0:00:14
   ------ --------------------------------- 5.8/38.0 MB 2.3 MB/s eta 0:00:14
   ------ --------------------------------- 6.3/38.0 MB 2.4 MB/s eta 0:00:14
   ------- -------------------------------- 6.8/38.0 MB 2.4 MB/s eta 0:00:14
   ------- -------------------------------- 7.3/38.0 MB 2.3 MB/s eta 0:00:14
   -------- ------------------------------- 7.9/38.0 MB 2.4 MB/s eta 0:00:13
   -------- ------------------------------- 8.1/38.0 MB 2.4 MB/s eta 0:00:13
   --------- ------------------------------ 8.7/38.0 MB 2.4 MB/s eta 0:00:13
   --------- ------------------------------ 9.2/38.0 MB 2.3 MB/s eta 0:00:13
   ---------- ----------------------------- 9.7/38.0 MB 2.3 MB/s eta 0:00:13
   ---------- ----------------------------- 10.2/38.0 MB 2.4 MB/s eta 0:00:12
   ----------- ---------------------------- 10.7/38.0 MB 2.3 MB/s eta 0:00:12
   ----------- ---------------------------- 11.3/38.0 MB 2.3 MB/s eta 0:00:12
   ------------ --------------------------- 11.8/38.0 MB 2.3 MB/s eta 0:00:12
   ------------ --------------------------- 12.1/38.0 MB 2.3 MB/s eta 0:00:12
   ------------- -------------------------- 12.6/38.0 MB 2.3 MB/s eta 0:00:11
   ------------- -------------------------- 13.1/38.0 MB 2.3 MB/s eta 0:00:11
   -------------- ------------------------- 13.6/38.0 MB 2.3 MB/s eta 0:00:11
   -------------- ------------------------- 14.2/38.0 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 14.7/38.0 MB 2.3 MB/s eta 0:00:10
   --------------- ------------------------ 15.2/38.0 MB 2.3 MB/s eta 0:00:10
   ---------------- ----------------------- 15.5/38.0 MB 2.3 MB/s eta 0:00:10
   ---------------- ----------------------- 16.0/38.0 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/38.0 MB 2.3 MB/s eta 0:00:10
   ----------------- ---------------------- 17.0/38.0 MB 2.3 MB/s eta 0:00:09
   ------------------ --------------------- 17.6/38.0 MB 2.3 MB/s eta 0:00:09
   ------------------- -------------------- 18.1/38.0 MB 2.4 MB/s eta 0:00:09
   ------------------- -------------------- 18.6/38.0 MB 2.3 MB/s eta 0:00:09
   -------------------- ------------------- 19.1/38.0 MB 2.3 MB/s eta 0:00:09
   -------------------- ------------------- 19.7/38.0 MB 2.3 MB/s eta 0:00:08
   --------------------- ------------------ 20.2/38.0 MB 2.3 MB/s eta 0:00:08
   --------------------- ------------------ 20.4/38.0 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 21.0/38.0 MB 2.3 MB/s eta 0:00:08
   ---------------------- ----------------- 21.5/38.0 MB 2.3 MB/s eta 0:00:08
   ----------------------- ---------------- 22.0/38.0 MB 2.3 MB/s eta 0:00:07
   ----------------------- ---------------- 22.5/38.0 MB 2.3 MB/s eta 0:00:07
   ------------------------ --------------- 23.1/38.0 MB 2.3 MB/s eta 0:00:07
   ------------------------ --------------- 23.6/38.0 MB 2.3 MB/s eta 0:00:07
   ------------------------- -------------- 24.1/38.0 MB 2.3 MB/s eta 0:00:06
   ------------------------- -------------- 24.6/38.0 MB 2.3 MB/s eta 0:00:06
   -------------------------- ------------- 25.2/38.0 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 25.7/38.0 MB 2.4 MB/s eta 0:00:06
   --------------------------- ------------ 26.0/38.0 MB 2.3 MB/s eta 0:00:06
   --------------------------- ------------ 26.5/38.0 MB 2.3 MB/s eta 0:00:05
   ---------------------------- ----------- 27.0/38.0 MB 2.3 MB/s eta 0:00:05
   ---------------------------- ----------- 27.5/38.0 MB 2.3 MB/s eta 0:00:05
   ----------------------------- ---------- 28.0/38.0 MB 2.3 MB/s eta 0:00:05
   ------------------------------ --------- 28.6/38.0 MB 2.4 MB/s eta 0:00:05
   ------------------------------ --------- 29.1/38.0 MB 2.3 MB/s eta 0:00:04
   ------------------------------- -------- 29.6/38.0 MB 2.4 MB/s eta 0:00:04
   ------------------------------- -------- 30.1/38.0 MB 2.3 MB/s eta 0:00:04
   -------------------------------- ------- 30.7/38.0 MB 2.4 MB/s eta 0:00:04
   -------------------------------- ------- 31.2/38.0 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 31.5/38.0 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 32.0/38.0 MB 2.3 MB/s eta 0:00:03
   ---------------------------------- ----- 32.5/38.0 MB 2.4 MB/s eta 0:00:03
   ---------------------------------- ----- 33.0/38.0 MB 2.4 MB/s eta 0:00:03
   ----------------------------------- ---- 33.6/38.0 MB 2.3 MB/s eta 0:00:02
   ----------------------------------- ---- 34.1/38.0 MB 2.3 MB/s eta 0:00:02
   ------------------------------------ --- 34.6/38.0 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 35.1/38.0 MB 2.4 MB/s eta 0:00:02
   ------------------------------------- -- 35.7/38.0 MB 2.4 MB/s eta 0:00:02
   -------------------------------------- - 36.2/38.0 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 36.7/38.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  37.2/38.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 38.0/38.0 MB 2.3 MB/s  0:00:16
Installing collected packages: polars
Successfully installed polars-1.32.3
Note: you may need to restart the kernel to use updated packages.

In [9]:
pip install fastexcel

Collecting fastexcel
  Downloading fastexcel-0.14.0-cp39-abi3-win_amd64.whl.metadata (3.5 kB)
Collecting pyarrow>=8.0.0 (from fastexcel)
  Downloading pyarrow-21.0.0-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Downloading fastexcel-0.14.0-cp39-abi3-win_amd64.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.1 MB ? eta -:--:--
   ---------------------------- ----------- 0.8/1.1 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 1.1/1.1 MB 2.3 MB/s  0:00:00
Downloading pyarrow-21.0.0-cp311-cp311-win_amd64.whl (26.2 MB)
   ---------------------------------------- 0.0/26.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/26.2 MB ? eta -:--:--
   - -------------------------------------- 1.0/26.2 MB 2.5 MB/s eta 0:00:10
   - -------------------------------------- 1.3/26.2 MB 2.5 MB/s eta 0:00:11
   --- ------------------------------------ 2.1/26.2 MB 2.4 MB/s eta 0:00:10
   --- ------------------------------------ 2.6/26.2 MB 2.5 MB/s eta 0:00:10
   ---- ----------------------------------- 3.1/26.2 MB 2.5 MB/s eta 0:00:10
   ----- ---------------------------------- 3.7/26.2 MB 2.5 MB/s eta 0:00:10
   ----- ---------------------------------- 3.9/26.2 MB 2.4 MB/s eta 0:00:10
   ------ --------------------------------- 4.5/26.2 MB 2.4 MB/s eta 0:00:09
   ------- -------------------------------- 5.2/26.2 MB 2.4 MB/s eta 0:00:09
   -------- ------------------------------- 5.8/26.2 MB 2.4 MB/s eta 0:00:09
   --------- ------------------------------ 6.0/26.2 MB 2.4 MB/s eta 0:00:09
   --------- ------------------------------ 6.6/26.2 MB 2.4 MB/s eta 0:00:09
   ---------- ----------------------------- 7.1/26.2 MB 2.4 MB/s eta 0:00:08
   ----------- ---------------------------- 7.6/26.2 MB 2.4 MB/s eta 0:00:08
   ------------ --------------------------- 8.1/26.2 MB 2.4 MB/s eta 0:00:08
   ------------- -------------------------- 8.7/26.2 MB 2.4 MB/s eta 0:00:08
   ------------- -------------------------- 9.2/26.2 MB 2.4 MB/s eta 0:00:07
   -------------- ------------------------- 9.7/26.2 MB 2.4 MB/s eta 0:00:07
   --------------- ------------------------ 10.2/26.2 MB 2.4 MB/s eta 0:00:07
   ---------------- ----------------------- 10.7/26.2 MB 2.4 MB/s eta 0:00:07
   ----------------- ---------------------- 11.3/26.2 MB 2.4 MB/s eta 0:00:07
   ----------------- ---------------------- 11.8/26.2 MB 2.4 MB/s eta 0:00:06
   ------------------ --------------------- 12.3/26.2 MB 2.4 MB/s eta 0:00:06
   ------------------- -------------------- 12.8/26.2 MB 2.4 MB/s eta 0:00:06
   -------------------- ------------------- 13.4/26.2 MB 2.4 MB/s eta 0:00:06
   --------------------- ------------------ 13.9/26.2 MB 2.4 MB/s eta 0:00:06
   --------------------- ------------------ 14.4/26.2 MB 2.4 MB/s eta 0:00:05
   ---------------------- ----------------- 14.9/26.2 MB 2.4 MB/s eta 0:00:05
   ----------------------- ---------------- 15.5/26.2 MB 2.4 MB/s eta 0:00:05
   ------------------------ --------------- 16.0/26.2 MB 2.4 MB/s eta 0:00:05
   ------------------------- -------------- 16.5/26.2 MB 2.4 MB/s eta 0:00:05
   ------------------------- -------------- 17.0/26.2 MB 2.4 MB/s eta 0:00:04
   -------------------------- ------------- 17.6/26.2 MB 2.4 MB/s eta 0:00:04
   --------------------------- ------------ 18.1/26.2 MB 2.4 MB/s eta 0:00:04
   ---------------------------- ----------- 18.6/26.2 MB 2.4 MB/s eta 0:00:04
   ----------------------------- ---------- 19.1/26.2 MB 2.4 MB/s eta 0:00:03
   ----------------------------- ---------- 19.7/26.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------ --------- 20.2/26.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------- -------- 20.4/26.2 MB 2.4 MB/s eta 0:00:03
   ------------------------------- -------- 21.0/26.2 MB 2.4 MB/s eta 0:00:03
   --------------------------------- ------ 21.8/26.2 MB 2.4 MB/s eta 0:00:02
   --------------------------------- ------ 22.0/26.2 MB 2.4 MB/s eta 0:00:02
   ---------------------------------- ----- 22.5/26.2 MB 2.4 MB/s eta 0:00:02
   ----------------------------------- ---- 23.3/26.2 MB 2.4 MB/s eta 0:00:02
   ------------------------------------ --- 23.9/26.2 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 24.4/26.2 MB 2.4 MB/s eta 0:00:01
   ------------------------------------- -- 24.9/26.2 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 25.2/26.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  25.7/26.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  26.2/26.2 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 26.2/26.2 MB 2.4 MB/s  0:00:10
Installing collected packages: pyarrow, fastexcel

   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   ---------------------------------------- 0/2 [pyarrow]
   -------------------- ------------------- 1/2 [fastexcel]
   ---------------------------------------- 2/2 [fastexcel]

Successfully installed fastexcel-0.14.0 pyarrow-21.0.0
Note: you may need to restart the kernel to use updated packages.

In [12]:
import polars as pl

hojas = ["Income Statement", "Balance Sheet", "Cash Flow", "Ratios"]



for hoja in hojas:
    print(f"Leyendo hoja: {hoja}")
    df = pl.read_excel(data_path, sheet_name=hoja)

    nombre_csv = f"{hoja}.csv".replace(" ", "_")
    df.write_csv(nombre_csv)
    print(f"Guardado: {nombre_csv}")
    
    
# df = pl.read_excel(
#     data_path,
#     sheet_id=0,          # o sheet_name="Hoja1"
#     # read_options={"dtype_backend": "pyarrow"}  # más flexible con nulos
# )

# print(df)

Could not determine dtype for column 21, falling back to string

Leyendo hoja: Income Statement
Guardado: Income_Statement.csv
Leyendo hoja: Balance Sheet
Guardado: Balance_Sheet.csv
Leyendo hoja: Cash Flow
Guardado: Cash_Flow.csv
Leyendo hoja: Ratios
Guardado: Ratios.csv

In [22]:
pd.read_csv("Ratios.csv")

,Ratios | TIKR.com,30/6/04,30/6/05,30/6/07,30/6/08,30/6/09,30/6/10,30/6/11,30/6/12,30/6/13,...,30/6/16,30/6/17,30/6/18,30/6/19,30/6/20,30/6/21,30/6/22,30/6/23,30/6/24,LTM
0,Return Ratios:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Return on Assets %,NaN,0.046868,-0.12324,0.079251,0.04815,0.094975,0.131694,0.176221,0.161163,...,0.137225,0.136724,0.135638,0.141103,0.11474,0.128594,0.108439,0.086302,0.087268,NaN
2,Return on Invested Capital %,0.013959,0.071712,-0.143022,0.126275,0.089752,0.158511,0.21566,0.276757,0.244078,...,0.19776,0.199656,0.193196,0.202725,0.173835,0.193879,0.160207,0.129892,0.126162,NaN
3,Return On Equity %,NaN,0.083124,-0.290219,0.167958,0.089392,0.160434,0.20892,0.277845,0.26271,...,0.210184,0.212945,0.215602,0.22705,0.179715,0.195025,0.188628,0.159251,0.146497,NaN
4,Normalized ROIC %,0.015116,0.072656,0.099171,0.129324,0.091143,0.159125,0.220423,0.282985,0.251334,...,0.198661,0.201232,0.195516,0.203661,0.191045,0.194065,0.160535,0.13041,0.127855,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Forward P/E Ratio,NaN,NaN,NaN,NaN,NaN,NaN,"11,52x",NaN,NaN,...,"17,64x","22,42x",NaN,NaN,"36,76x","38,02x","20,16x","22,62x",NaN,"37,31x"
76,Forward Dividend Yield,NaN,NaN,NaN,0.0368,NaN,NaN,0.0476,NaN,NaN,...,0.0512,0.0361,NaN,NaN,0.0171,0.0112,0.0167,0.015,NaN,0.0096
77,Forward Earning Yield,NaN,NaN,NaN,NaN,NaN,NaN,0.0868,NaN,NaN,...,0.0567,0.0446,NaN,NaN,0.0272,0.0263,0.0496,0.0442,NaN,0.0268
78,PEG Ratio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Normalized PEG Ratio,"0,15x",NaN,NaN,"0,46x",NaN,"1,26x","0,92x",NaN,NaN,...,"1,31x","2,74x",NaN,NaN,"6,04x","5,07x","2,20x","2,08x",NaN,"4,52x"