# Comprobamos que todos los ficheros tienen los mismos campos de información

Nos interesa recuperar la siguiente información: 

- Income Statement:
    * Total Renevues: Total de ingresos de la empresa
- Cash Flow: 
    * % Free Cash Flow Margins: Margen del flujo de caja libre. 
- Ratios: 

    - Return Ratios: Ratios de rentabilidad
        * Return on Assets %: Rentabilidad sobre los activos
        * Return on Invested Capital %: Rentabilidad sobre el capital.
        * Return On Equity %: Rentabilidad sobre los recursos propios.
        * Normalized ROIC %: Rentabilidad sobre las acciones orginarias.

    - Análisis de los márgenes:
        * Gross Profit Margin %: Margen de beneficio bruto.
        * EBITDA Margin %: Margen EBITDA (EBIT + Depreciaciones y Amortizaciones)
        * Net Income Margin %: Margen de beneficio neto
        * Normalized Net Income Margin %: Margen de beneficio neto normalizado
    
    - Short Term Liquidity: Solvencia a corto plazo
        * Current Ratio: Ratio de liquidez (Activos actuales / pasivos actuales)
    
    - Long-Term Liquidity: Solvencia a largo plazo
        * Total Debt / Equity: Deuda total / Fondos propios

In [1]:
import os
os.chdir("C:/TFM/tfm_env/")

import polars as pl
import pandas as pd

In [411]:
# %%writefile src/preprocessdata/utils.py

import pandas as pd
from dataclasses import dataclass
from typing import Any, Callable, Optional, Iterable, Literal
from pandas import DataFrame
import polars as pl
import uuid

# ------------------------------------------------------------
# Tipado estilo steps
# ------------------------------------------------------------

Reader = Callable[[], pd.DataFrame]
Step = Callable[[pd.DataFrame], pd.DataFrame]
Writer = Callable[[pd.DataFrame], None]




def chain(df: pd.DataFrame, *steps: Step) -> pd.DataFrame:
    """
    Aplica los steps en orden usando .pipe para un estilo encadenado.
    """
    for s in steps:
        df = df.pipe(s)
    return df


def pump_load(reader: Reader) -> Callable[[], DataFrame]:
    def _apply() -> DataFrame:
        return reader()
    return _apply


# def func():
#     @requ
#     def _apply(df)-> pd.DataFrame:


# ----------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class PumpConfig:
    base_path: str
    sheet_name: str = None
    sheet_list: list = None
    format: Literal["parquet", "csv", "json", "excel"] = "csv"

@dataclass(frozen=True)
class SinkConfig:
    base_path: str
    mode: Literal["overwrite", "append"] = "overwrite"
    format: Literal["parquet", "csv", "json"] = "csv"


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

def _join_path(base: str, name_or_path: str) -> str:
    if name_or_path.startswith(("s3://", "s3a://", "hdfs://", "dbfs:/", "/")):
        return name_or_path
    return f"{base.rstrip('/')}/{name_or_path.lstrip('/')}"


def _select_columns(df: pd.DataFrame, columns: Optional[Iterable[str]]) -> pd.DataFrame:
    if columns is None:
        return df
    cols = list(columns)
    # read_parquet y read_csv soportan proyección; read_json no siempre -> seleccionamos después
    return df.loc[:, [c for c in cols if c in df.columns]]


def _basename(fmt: str) -> str:
    return f"part-{uuid.uuid4().hex}.{fmt}"



def pump_load(loader):
    def _apply():
        return loader()
    return _apply()

# ----------------------------------------------------------------------
# Loader principal (pandas)
# ----------------------------------------------------------------------

def make_loader(
                cfg: PumpConfig,
                name_or_path: str,
                ) -> Reader:
    
    path = _join_path(cfg.base_path, name_or_path)
    fmt = cfg.format.lower()

    def _load() -> pd.DataFrame:
        if fmt == "parquet":
            # pandas puede proyectar columnas en el propio lector
            df = pl.read_parquet(
                path)
            
            df = df.to_pandas()
            return df
        elif fmt == "csv":
            df = pl.read_csv(
                path
                )
            df = df.to_pandas()
            return df
        elif fmt == "json":
            # JSON es variado; pasa flags en context["read_json_kwargs"] (p.ej. lines=True)
            df = pl.read_json(
                path
            )
            df = df.to_pandas()
            df = _select_columns(df, columns)
            return df
        elif fmt == "excel":
            
            if cfg.sheet_name is not None:
                df = pl.read_excel(
                    path,
                    sheet_name=cfg.sheet_name
                )
            else:
                df = pl.read_excel(
                    path
                )
            df = df.to_pandas()
            return df
            
        else:
            raise ValueError(f"Formato no soportado: {fmt}")


    return _load




# ------------------------------------------------------------
# TAPS: efectos controlados (escriben / registran y devuelven DF)
# ------------------------------------------------------------
def tap_write(writer: Writer) -> Step:
    def _apply(df: pd.DataFrame) -> pd.DataFrame:
        writer(df)  # efecto deliberado
        return df
    return _apply




# ------------------------------------------------------------
# Writer principal
# ------------------------------------------------------------
def make_writer(cfg: SinkConfig, name: str, partitionBy: Iterable[str] = ()) -> Writer:
    path = _join_path(cfg.base_path, name)
    fmt = cfg.format.lower()
    parts = list(partitionBy)

    def _writer_csv_or_json(df: pd.DataFrame, ext: str) -> None:
        import fsspec  # ligero; útil para s3/hdfs/file
        fs, _, _ = fsspec.get_fs_token_paths(path)
        base_dir = path
        if cfg.mode == "overwrite" and fs.exists(base_dir):
            fs.rm(base_dir, recursive=True)
        fs.mkdirs(base_dir, exist_ok=True)

        if parts:
            # Escribimos un archivo por partición en subdirectorios estilo col=val/…
            grouped = df.groupby(parts, dropna=False, sort=False)
            for keys, sub in grouped:
                # keys puede ser escalar o tupla
                keys = (keys,) if not isinstance(keys, tuple) else keys
                subdir = "/".join(f"{col}={val}" for col, val in zip(parts, keys))
                full_dir = f"{base_dir.rstrip('/')}/{subdir}"
                fs.mkdirs(full_dir, exist_ok=True)
                file_path = path
                with fs.open(file_path, "wb") as f:
                    if ext == "csv":
                        sub.to_csv(f, index=False)
                    else:
                        # Para JSON, lo más práctico en pipelines: lines=True
                        sub.to_json(f, orient="records", lines=True)
        else:
            # Dataset “sin partición”: escribimos un archivo por llamada (append = archivo nuevo)
            file_path = path
            with fs.open(file_path, "wb") as f:
                if ext == "csv":
                    df.to_csv(f, index=False)
                else:
                    df.to_json(f, orient="records", lines=True)

    def _writer(df: pd.DataFrame) -> None:
        if fmt == "parquet":
            _writer_parquet(df)
        elif fmt == "csv":
            _writer_csv_or_json(df, "csv")
        elif fmt == "json":
            _writer_csv_or_json(df, "json")

        else:
            raise ValueError(f"Formato no soportado: {cfg.format}")

    return _writer

In [406]:
# simple_file_writer.py
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Literal, Optional
import pandas as pd

Writer = Callable[[pd.DataFrame], None]

@dataclass(frozen=True)
class SinkConfig:
    base_path: Path
    format: Literal["parquet", "csv", "json"] = "parquet"
    mode:   Literal["overwrite", "append"] = "overwrite"
    # JSON
    json_lines: bool = True     # True => NDJSON (recomendado para append)
    # CSV
    encoding: str = "utf-8"
    newline: str = ""
    # Parquet
    parquet_engine: str = "pyarrow"  # o "fastparquet"

def _ensure_suffix(path: Path, fmt: str) -> Path:
    ext = { "parquet": ".parquet", "csv": ".csv", "json": ".json" }[fmt]
    return path if path.suffix.lower() == ext else path.with_suffix(ext)

def make_writer(cfg: SinkConfig, name: str) -> Writer:
    """Crea un writer que guarda SIEMPRE en un único archivo local."""
    dest = _ensure_suffix(Path(cfg.base_path + "/" + name), cfg.format)
    dest.parent.mkdir(parents=True, exist_ok=True)

    def _writer(df: pd.DataFrame) -> None:
        if dest.exists() and dest.is_dir():
            raise IsADirectoryError(f"'{dest}' es un directorio; se esperaba un archivo.")

        if cfg.format == "csv":
            if cfg.mode == "overwrite":
                df.to_csv(dest, index=False, encoding=cfg.encoding)
            else:  # append
                header = not dest.exists()
                df.to_csv(dest, mode="a", header=header, index=False,
                          encoding=cfg.encoding)

        elif cfg.format == "json":
            if cfg.json_lines:  # NDJSON: perfecto para append
                mode = "w" if cfg.mode == "overwrite" else "a"
                with open(dest, mode, encoding=cfg.encoding, newline=cfg.newline) as f:
                    df.to_json(f, orient="records", lines=True, force_ascii=False)
            else:
                # JSON como array. Append simple = leer + concatenar + reescribir.
                if cfg.mode == "append" and dest.exists():
                    import json
                    with open(dest, "r", encoding=cfg.encoding) as f:
                        existing = json.load(f)
                    if not isinstance(existing, list):
                        raise ValueError("El JSON existente no es un array; no puedo hacer append.")
                    existing.extend(df.to_dict(orient="records"))
                    with open(dest, "w", encoding=cfg.encoding, newline=cfg.newline) as f:
                        json.dump(existing, f, ensure_ascii=False)
                else:
                    df.to_json(dest, orient="records", force_ascii=False)

        elif cfg.format == "parquet":
            if cfg.mode == "append" and dest.exists():
                # Estrategia simple: leer existente, concatenar y reescribir.
                prev = pd.read_parquet(dest, engine=cfg.parquet_engine)
                out = pd.concat([prev, df], ignore_index=True)
                out.to_parquet(dest, index=False, engine=cfg.parquet_engine)
            else:
                df.to_parquet(dest, index=False, engine=cfg.parquet_engine)

        else:
            raise ValueError(f"Formato no soportado: {cfg.format}")

    return _writer

In [385]:
base_dir = "C:/TFM/tfm_env/data/01_raw/prueba/"
ext="csv"
f"{base_dir.rstrip('/')}"

'C:/TFM/tfm_env/data/01_raw/prueba'

In [ ]:
# etl/sink_pd.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Callable, Dict, Iterable, Optional, Literal

import pandas as pd


def tap_metrics(log: Callable[[Dict[str, Any]], None]) -> Step:
    def _apply(df: pd.DataFrame) -> pd.DataFrame:
        rows = len(df)
        distinct_id = df["id"].nunique(dropna=True) if "id" in df.columns else None
        log({"rows": rows, "distinct_id": distinct_id})
        return df
    return _apply

# ------------------------------------------------------------
# Config del sink y utilidades
# ------------------------------------------------------------

In [ ]:
# etl/loader_pd.py
from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Callable, Optional, Iterable, Literal

import pandas as pd

Reader = Callable[[], pd.DataFrame]

# ----------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------

@dataclass(frozen=True)
class PumpConfig:
    base_path: str
    context: Any = None  # p.ej. dict con storage_options/kwargs
    format: Literal["parquet", "csv", "json"] = "csv"

# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

def _join_path(base: str, name_or_path: str) -> str:
    if name_or_path.startswith(("s3://", "s3a://", "hdfs://", "dbfs:/", "/")):
        return name_or_path
    return f"{base.rstrip('/')}/{name_or_path.lstrip('/')}"


def _select_columns(df: pd.DataFrame, columns: Optional[Iterable[str]]) -> pd.DataFrame:
    if columns is None:
        return df
    cols = list(columns)
    # read_parquet y read_csv soportan proyección; read_json no siempre -> seleccionamos después
    return df.loc[:, [c for c in cols if c in df.columns]]

# ----------------------------------------------------------------------
# Loader principal (pandas)
# ----------------------------------------------------------------------

def make_loader(
                cfg: PumpConfig,
                name_or_path: str,
                *,
                columns: Optional[Iterable[str]] = None,
                alias: Optional[str] = None,
                ) -> Reader:
    
    path = _join_path(cfg.base_path, name_or_path)
    fmt = cfg.format.lower()

    def _load() -> pd.DataFrame:
        if fmt == "parquet":
            # pandas puede proyectar columnas en el propio lector
            df = pd.read_parquet(
                path,
                columns=list(columns) if columns else None,)
        elif fmt == "csv":
            df = pd.read_csv(
                path,
                usecols=list(columns) if columns else None,
                s
            )
        elif fmt == "json":
            # JSON es variado; pasa flags en context["read_json_kwargs"] (p.ej. lines=True)
            df = pd.read_json(
                path
            )
            df = _select_columns(df, columns)
        else:
            raise ValueError(f"Formato no soportado: {fmt}")

        # “Alias” no existe en pandas; lo guardamos en metadatos del DF
        if alias:
            try:
                df.attrs["alias"] = alias
            except Exception:
                pass
        return df

    return _load

In [2]:
from src.financial_metrics_check import *

In [434]:


def is_ratio_sheet(file):
    if file[:-4].endswith("Ratios"):
        return True
    return False

def is_cash_flow_sheet(file):
    if file[:-4].endswith("Cash Flow"):
        return True
    return False

def check_field_in_ratio_sheet(df, field):

    field_list = df['Ratios | TIKR.com'].apply(lambda x: x.lower()).tolist()
    return field.lower() in field_list


def is_valid_file_ratio(file_path, ratio_list):

    for field in ratio_list:
        if not check_field_in_ratio_sheet(file_path, field):
            return False
    return True

def check_field_in_cash_flow_sheet(df, field):

    field_list = df['Cash Flow | TIKR.com'].apply(lambda x: x.lower()).tolist()
    return field.lower() in field_list


def is_valid_file_cash_flow(file_path, cash_flow_list):

    for field in cash_flow_list:
        if not check_field_in_cash_flow_sheet(file_path, field):
            return False
    return True


def check_field_in_income_statement(df, field):

    field_list = df['Income Statement | TIKR.com'].apply(lambda x: x.lower()).tolist()
    return field.lower() in field_list


def is_valid_file_income_statement(file_path, income_statement_list):

    for field in income_statement_list:
        if not check_field_in_income_statement(file_path, field):
            return False
    return True



def extract_tikr(file_name='file_name.xlsx'):
    
    return file_name.split("-")[1].strip()
    
    
def extract_currency(file_name='file_name.xlsx'):
    
    return file_name.split("-")[0].strip()
    
    
ratios_list = ["Return on Assets %", "Return on Invested Capital %", 
               "Return On Equity %", "Normalized ROIC %", "Gross Profit Margin %", 
               "EBITDA Margin %", "Net Income Margin %", 
               "Normalized Net Income Margin %", "Current Ratio", 
               "Total Debt / Equity"]

In [431]:
from pathlib import Path
Path("C:/TFM/tfm_env/data/01_raw/").joinpath("prueba/").as_posix()

'C:/TFM/tfm_env/data/01_raw/prueba'

In [ ]:
pump_raw_historical_financial_statement_ratios = PumpConfig("C:/TFM/tfm_env/data/01_raw/01.3 - HistoricoEstadosFinancieros/", format="excel", sheet_name="Ratios")
pump_raw_historical_financial_statement = PumpConfig("C:/TFM/tfm_env/data/01_raw/01.3 - HistoricoEstadosFinancieros/", format="excel", sheet_list=["Ratios", "Cash Flow"])



raw_sink = SinkConfig(base_path="data/01_raw/", format="csv")

def valid_files_gen(cfg: PumpConfig) -> str:
    path = Path(cfg.base_path)

    for sector in [s for s in os.listdir(path)]: 
        sector_path = path.joinpath(sector)
        for file in os.listdir(sector_path):
            print(file)

            file_list = []
            
            for sheet in cfg.sheet_list:

                file_info = {
                    "base_path": path,
                    "sector": sector,
                    "sheet": sheet,
                    "file": file
                }
                
                df = pl.read_excel(f"{path}/{sector}/{file}".format_map(file_info), sheet = file_info["sheet"])
                
                
                
                
                
                # chain(
#     pump_load(make_loader(
#                 cfg= pump_raw_historical_financial_statement,
#                 name_or_path= "{sector_dir}{file}".format_map(file_info)
#                 )),
    
#     tap_write(make_writer(cfg=raw_sink, name="prueba/prueba2"))
# )



gen = valid_files_gen(pump_raw_historical_financial_statement)


# def step_fun() -> DataFrame:
#     def _apply(df):
#         return df
#     return _apply
from datetime import datetime


# def step_check_valid_historical_period(sheet_name) -> DataFrame:
#     def _apply(df):
        
#         title_idx_cash_flow = sheet_name + " | TIKR.com"

#         l = df.keys().tolist()
#         l.remove(sheet_name + " | TIKR.com")
#         l.remove("LTM")
#         l = [datetime.strptime(d, "%d/%m/%y") for d in l]
#         if (max(l).year<2024) or (len(l)<16):
#             continue
        

        
#         return df
#     return _apply






# # # Eslabón más bajo
# chain(
#     pump_load(make_loader(
#                 cfg= pump_raw_historical_financial_statement,
#                 name_or_path= "{sector_dir}{file}".format_map(file_info)
#                 )),
    
#     tap_write(make_writer(cfg=raw_sink, name="prueba/prueba2"))
# )

AUD - CHC - Financials (30.6.07 - 30.6.24).xlsx
AUD - GPT - Financials (31.12.04 - 31.12.24).xlsx
AUD - MGR - Financials (30.6.03 - 30.6.24).xlsx
AUD - SGP - Financials (30.6.04 - 30.6.24).xlsx
CAD - HR.UN - Financials (31.12.05 - 31.12.24).xlsx
EUR - COV - Financials (31.12.05 - 31.12.24).xlsx
EUR - ICAD - Financials (31.12.05 - 31.12.24).xlsx
EUR - MRL - Financials (31.12.13 - 31.12.24).xlsx
GBP - BLND - Financials (31.3.06 - 31.3.25).xlsx
GBP - LAND - Financials (31.3.06 - 31.3.25).xlsx
JPY - 3279 - Financials (30.11.12 - 30.11.24).xlsx
JPY - 3309 - Financials (31.10.15 - 31.10.24).xlsx
JPY - 3462 - Financials (31.8.14 - 31.8.24).xlsx
JPY - 8960 - Financials (30.11.06 - 30.11.24).xlsx
JPY - 8972 - Financials (31.10.06 - 31.10.24).xlsx
JPY - 8984 - Financials (31.8.09 - 31.8.24).xlsx
MXN - DANHOS 13 - Financials (31.12.13 - 31.12.24).xlsx
MXN - FUNO 11 - Financials (31.12.11 - 31.12.24).xlsx
MYR - KLCC - Financials (31.3.05 - 31.12.24).xlsx
SGD - N2IU - Financials (31.3.11 - 31.3.25).xlsx
SGD - T82U - Financials (30.9.05 - 31.12.24).xlsx
TRY - ZRGYO - Financials (31.12.18 - 31.12.24).xlsx
USD - BNL - Financials (31.12.15 - 31.12.24).xlsx
USD - EPRT - Financials (31.12.16 - 31.12.24).xlsx
USD - ESBA - Financials (31.12.11 - 31.12.24).xlsx
USD - LMT - Financials (31.12.05 - 31.12.24).xlsx
USD - WPC - Financials (31.12.05 - 31.12.24).xlsx
ZAR - GRT - Financials (30.6.05 - 30.6.24).xlsx
AED - TALABAT - Financials (31.12.22 - 31.12.24).xlsx
AUD - BRG - Financials (30.6.04 - 30.6.24).xlsx
AUD - PMV - Financials (30.6.03 - 31.7.24).xlsx
BRL - SMFT3 - Financials (31.12.16 - 31.12.24).xlsx
BRL - VBBR3 - Financials (31.12.12 - 31.12.24).xlsx
CAD - DOL - Financials (31.1.09 - 31.1.25).xlsx
CAD - HBM - Financials (31.12.05 - 31.12.24).xlsx
CAD - MG - Financials (31.12.05 - 31.12.24).xlsx
CHF - AVOL - Financials (31.12.05 - 31.12.24).xlsx
CHF - UHR - Financials (31.12.05 - 31.12.24).xlsx
CLP - COPEC - Financials (31.12.06 - 31.12.24).xlsx
CNY - 000559 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000564 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000625 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000887 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002031 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002032 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002085 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002472 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 002850 - Financials (31.12.11 - 31.12.24).xlsx
CNY - 300979 - Financials (31.12.17 - 31.12.24).xlsx
CNY - 600690 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600699 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600839 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600859 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600933 - Financials (31.12.13 - 31.12.24).xlsx
CNY - 601777 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 601799 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 601888 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 603129 - Financials (31.12.13 - 31.12.24).xlsx
CNY - 603486 - Financials (31.12.13 - 31.12.24).xlsx
CNY - 603786 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 688169 - Financials (31.12.16 - 31.12.24).xlsx
CNY - 688819 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 689009 - Financials (31.12.16 - 31.12.24).xlsx
DKK - GN - Financials (31.12.05 - 31.12.24).xlsx
EUR - ADS - Financials (31.12.05 - 31.12.24).xlsx
EUR - AMS - Financials (31.12.06 - 31.12.24).xlsx
EUR - BAIN - Financials (31.3.06 - 31.3.25).xlsx
EUR - BELA - Financials (30.6.05 - 31.12.24).xlsx
EUR - BRE - Financials (31.12.05 - 31.12.24).xlsx
EUR - CDI - Financials (31.12.05 - 31.12.24).xlsx
EUR - DIE - Financials (31.12.05 - 31.12.24).xlsx
EUR - ITX - Financials (31.1.06 - 31.1.25).xlsx
EUR - KER - Financials (31.12.05 - 31.12.24).xlsx
EUR - ML - Financials (31.12.05 - 31.12.24).xlsx
EUR - PETG - Financials (31.12.09 - 31.12.24).xlsx
EUR - PIRC - Financials (31.12.05 - 31.12.24).xlsx
EUR - PRX - Financials (31.3.17 - 31.3.25).xlsx
EUR - RACE - Financials (31.12.12 - 31.12.24).xlsx
EUR - RNO - Financials (31.12.05 - 31.12.24).xlsx
EUR - SHA0 - Financials (31.12.11 - 31.12.24).xlsx
EUR - SK - Financials (31.12.05 - 31.12.24).xlsx
EUR - STLAM - Financials (31.12.05 - 31.12.24).xlsx
EUR - TUI1 - Financials (31.12.04 - 30.9.24).xlsx
EUR - ZAL - Financials (31.12.10 - 31.12.24).xlsx
EUR - ZO1 - Financials (31.12.06 - 31.12.20).xlsx
GBP - BRBY - Financials (31.3.06 - 31.3.25).xlsx
GBP - BTRW - Financials (30.6.05 - 30.6.24).xlsx
GBP - DNLM - Financials (30.6.05 - 30.6.24).xlsx
GBP - ENT - Financials (31.12.05 - 31.12.24).xlsx
GBP - FRAS - Financials (30.4.05 - 30.4.24).xlsx
GBP - TW. - Financials (31.12.04 - 31.12.23).xlsx
GBP - WTB - Financials (28.2.06 - 28.2.25).xlsx
HKD - 1070 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1128 - Financials (31.12.08 - 31.12.24).xlsx
HKD - 1364 - Financials (31.12.21 - 31.12.24).xlsx
HKD - 175 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1999 - Financials (31.3.06 - 31.3.25).xlsx
HKD - 2097 - Financials (31.12.21 - 31.12.24).xlsx
HKD - 2333 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 27 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 6181 - Financials (31.12.21 - 31.12.24).xlsx
HKD - 780 - Financials (31.12.15 - 31.12.24).xlsx
HKD - 9992 - Financials (31.12.17 - 31.12.24).xlsx
IDR - BELI - Financials (31.12.19 - 31.12.24).xlsx
INR - 500086 - Financials (31.3.06 - 31.3.25).xlsx
INR - 500182 - Financials (31.3.06 - 31.3.25).xlsx
INR - 500238 - Financials (31.3.06 - 31.3.25).xlsx
INR - 500251 - Financials (31.3.06 - 31.3.25).xlsx
INR - 502355 - Financials (31.3.06 - 31.3.25).xlsx
INR - 505200 - Financials (31.3.04 - 31.3.25).xlsx
INR - 521238 - Financials (31.3.08 - 31.3.25).xlsx
INR - BAJAJ-AUTO - Financials (31.3.06 - 31.3.25).xlsx
INR - ENDURANCE - Financials (31.3.12 - 31.3.25).xlsx
INR - ETERNAL - Financials (31.3.19 - 31.3.25).xlsx
INR - HYUNDAI - Financials (31.3.21 - 31.3.25).xlsx
INR - JUBLFOOD - Financials (31.3.06 - 31.3.25).xlsx
INR - KALYANKJIL - Financials (31.3.18 - 31.3.25).xlsx
INR - METROBRAND - Financials (31.3.19 - 31.3.25).xlsx
INR - MRF - Financials (30.9.05 - 31.3.25).xlsx
INR - MSUMI - Financials (31.3.21 - 31.3.25).xlsx
INR - SUNDRMFAST - Financials (31.3.06 - 31.3.25).xlsx
INR - TIINDIA - Financials (31.3.15 - 31.3.25).xlsx
JPY - 2282 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 2726 - Financials (28.2.06 - 28.2.25).xlsx
JPY - 3086 - Financials (29.2.08 - 28.2.25).xlsx
JPY - 3099 - Financials (31.3.09 - 31.3.25).xlsx
JPY - 3116 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 3350 - Financials (31.8.08 - 31.12.24).xlsx
JPY - 3397 - Financials (31.3.08 - 31.3.25).xlsx
JPY - 4732 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 4755 - Financials (31.12.05 - 31.12.24).xlsx
JPY - 5101 - Financials (31.3.05 - 31.12.24).xlsx
JPY - 5108 - Financials (31.12.05 - 31.12.24).xlsx
JPY - 5947 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 6460 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 6755 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 6758 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 6923 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7203 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7211 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7269 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7270 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7272 - Financials (31.12.05 - 31.12.24).xlsx
JPY - 7282 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7453 - Financials (28.2.05 - 31.8.24).xlsx
JPY - 7550 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7832 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 7936 - Financials (31.3.05 - 31.12.24).xlsx
JPY - 7951 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8227 - Financials (28.2.06 - 28.2.25).xlsx
JPY - 8233 - Financials (28.2.06 - 28.2.25).xlsx
KRW - A180640 - Financials (31.12.13 - 31.12.24).xlsx
KRW - A257720 - Financials (31.12.19 - 31.12.24).xlsx
MXN - LIVEPOL C-1 - Financials (31.12.05 - 31.12.24).xlsx
MYR - GENM - Financials (31.12.05 - 31.12.24).xlsx
MYR - GENTING - Financials (31.12.05 - 31.12.24).xlsx
PLN - ALE - Financials (31.12.17 - 31.12.24).xlsx
PLN - LPP - Financials (31.12.05 - 31.1.25).xlsx
SEK - ASMDEE B - Financials (31.3.22 - 31.3.25).xlsx
SEK - BETS B - Financials (31.12.05 - 31.12.24).xlsx
SEK - CLAS B - Financials (30.4.06 - 30.4.25).xlsx
SEK - THULE - Financials (31.12.11 - 31.12.24).xlsx
SGD - G13 - Financials (31.12.05 - 31.12.24).xlsx
TRY - TOASO - Financials (31.12.05 - 31.12.24).xlsx
TWD - 1476 - Financials (31.12.06 - 31.12.24).xlsx
TWD - 2258 - Financials (31.12.21 - 31.12.24).xlsx
TWD - 6890 - Financials (31.12.21 - 31.12.24).xlsx
TWD - 8111 - Financials (31.12.09 - 31.12.24).xlsx
TWD - 8114 - Financials (31.12.09 - 31.12.24).xlsx
TWD - 9904 - Financials (31.12.06 - 31.12.24).xlsx
TWD - 9910 - Financials (31.12.06 - 31.12.24).xlsx
USD - 1114 - Financials (31.12.05 - 31.12.24).xlsx
USD - 601965 - Financials (31.12.08 - 31.12.24).xlsx
USD - 603596 - Financials (31.12.13 - 31.12.24).xlsx
USD - ALL - Financials (31.12.05 - 31.12.24).xlsx
USD - AMZN - Financials (31.12.05 - 31.12.24).xlsx
USD - ANF - Financials (31.1.06 - 31.1.25).xlsx
USD - APTV - Financials (31.12.09 - 31.12.24).xlsx
USD - AZO - Financials (31.8.05 - 31.8.24).xlsx
USD - BBWI - Financials (31.1.06 - 31.1.25).xlsx
USD - BBY - Financials (28.2.05 - 31.1.25).xlsx
USD - BIRK - Financials (30.9.20 - 30.9.24).xlsx
USD - BWA - Financials (31.12.05 - 31.12.24).xlsx
USD - CAKE - Financials (31.12.05 - 31.12.24).xlsx
USD - CAVA - Financials (31.12.21 - 31.12.24).xlsx
USD - CCL - Financials (30.11.05 - 30.11.24).xlsx
USD - CMG - Financials (31.12.05 - 31.12.24).xlsx
USD - CRC - Financials (31.12.11 - 31.12.24).xlsx
USD - CROX - Financials (31.12.05 - 31.12.24).xlsx
USD - CVCO - Financials (31.3.06 - 31.3.25).xlsx
USD - CZR - Financials (31.12.12 - 31.12.24).xlsx
USD - DDS - Financials (31.1.06 - 31.1.25).xlsx
USD - DRI - Financials (31.5.05 - 31.5.24).xlsx
USD - EAT - Financials (30.6.05 - 30.6.24).xlsx
USD - ETSY - Financials (31.12.12 - 31.12.24).xlsx
USD - EVO - Financials (31.12.12 - 31.12.24).xlsx
USD - FL - Financials (31.1.06 - 31.1.25).xlsx
USD - FLUT - Financials (31.12.05 - 31.12.24).xlsx
USD - FND - Financials (31.12.11 - 31.12.24).xlsx
USD - FTDR - Financials (31.12.15 - 31.12.24).xlsx
USD - GAP - Financials (31.1.06 - 31.1.25).xlsx
USD - GENI - Financials (31.12.19 - 31.12.24).xlsx
USD - GLBE - Financials (31.12.18 - 31.12.24).xlsx
USD - GME - Financials (31.1.06 - 31.1.25).xlsx
USD - GNTX - Financials (31.12.05 - 31.12.24).xlsx
USD - GRMN - Financials (31.12.05 - 31.12.24).xlsx
USD - GTX - Financials (31.12.15 - 31.12.24).xlsx
USD - H - Financials (31.12.07 - 31.12.24).xlsx
USD - HD - Financials (31.1.06 - 31.1.25).xlsx
USD - HGV - Financials (31.12.13 - 31.12.24).xlsx
USD - JD - Financials (31.12.11 - 31.12.24).xlsx
USD - KBH - Financials (30.11.05 - 30.11.24).xlsx
USD - KMX - Financials (28.2.06 - 28.2.25).xlsx
USD - LCID - Financials (31.12.19 - 31.12.24).xlsx
USD - LCII - Financials (31.12.05 - 31.12.24).xlsx
USD - LEA - Financials (31.12.05 - 31.12.24).xlsx
USD - LEN - Financials (30.11.05 - 30.11.24).xlsx
USD - LI - Financials (31.12.18 - 31.12.24).xlsx
USD - LKQ - Financials (31.12.05 - 31.12.24).xlsx
USD - LTH - Financials (31.12.18 - 31.12.24).xlsx
USD - LULU - Financials (31.1.06 - 31.1.25).xlsx
USD - LVS - Financials (31.12.05 - 31.12.24).xlsx
USD - MAR - Financials (31.12.05 - 31.12.24).xlsx
USD - MCD - Financials (31.12.05 - 31.12.24).xlsx
USD - MNSO - Financials (30.6.18 - 31.12.24).xlsx
USD - MOD - Financials (31.3.06 - 31.3.25).xlsx
USD - MRP - Financials (31.12.23 - 31.12.24).xlsx
USD - MUSA - Financials (31.12.10 - 31.12.24).xlsx
USD - NKE - Financials (31.5.05 - 31.5.24).xlsx
USD - ONON - Financials (31.12.19 - 31.12.24).xlsx
USD - OSW - Financials (31.12.16 - 31.12.24).xlsx
USD - PATK - Financials (31.12.05 - 31.12.24).xlsx
USD - PLUS - Financials (31.3.06 - 31.3.25).xlsx
USD - PRDO - Financials (31.12.05 - 31.12.24).xlsx
USD - SBUX - Financials (30.9.05 - 30.9.24).xlsx
USD - SGI - Financials (31.12.05 - 31.12.24).xlsx
USD - SN - Financials (31.12.20 - 31.12.24).xlsx
USD - STRA - Financials (31.12.05 - 31.12.24).xlsx
USD - SW - Financials (31.12.06 - 31.12.24).xlsx
USD - TCOM - Financials (31.12.05 - 31.12.24).xlsx
USD - TMHC - Financials (31.12.10 - 31.12.24).xlsx
USD - TOL - Financials (31.10.05 - 31.10.24).xlsx
USD - TSCO - Financials (31.12.05 - 31.12.24).xlsx
USD - ULTA - Financials (31.1.06 - 31.1.25).xlsx
USD - VFC - Financials (31.12.06 - 31.3.25).xlsx
USD - VIK - Financials (31.12.21 - 31.12.24).xlsx
USD - W - Financials (31.12.12 - 31.12.24).xlsx
USD - WING - Financials (31.12.12 - 31.12.24).xlsx
USD - WYNN - Financials (31.12.05 - 31.12.24).xlsx
USD - XPEV - Financials (31.12.18 - 31.12.24).xlsx
USD - YETI - Financials (31.12.13 - 31.12.24).xlsx
USD - ZGN - Financials (31.12.18 - 31.12.24).xlsx
ZAR - TFG - Financials (31.3.06 - 31.3.25).xlsx
ZAR - WHL - Financials (30.6.05 - 30.6.24).xlsx
ARS - TGSU2 - Financials (31.12.05 - 31.12.24).xlsx
ARS - YPFD - Financials (31.12.05 - 31.12.24).xlsx
AUD - ALD - Financials (31.12.05 - 31.12.24).xlsx
AUD - INA - Financials (30.6.06 - 30.6.24).xlsx
AUD - NHC - Financials (31.7.02 - 31.7.24).xlsx
AUD - STO - Financials (31.12.03 - 31.12.24).xlsx
AUD - WDS - Financials (31.12.05 - 31.12.24).xlsx
AUD - WHC - Financials (30.6.07 - 30.6.25).xlsx
BRL - CSAN3 - Financials (30.4.05 - 31.12.24).xlsx
BRL - PETR4 - Financials (31.12.05 - 31.12.24).xlsx
BRL - PRIO3 - Financials (31.12.07 - 31.12.24).xlsx
CAD - ATH - Financials (31.12.08 - 31.12.24).xlsx
CAD - CCO - Financials (31.12.05 - 31.12.24).xlsx
CAD - CNQ - Financials (31.12.05 - 31.12.24).xlsx
CAD - CNR - Financials (31.12.05 - 31.12.24).xlsx
CAD - CVE - Financials (31.12.08 - 31.12.24).xlsx
CAD - ENB - Financials (31.12.05 - 31.12.24).xlsx
CAD - IMO - Financials (31.12.05 - 31.12.24).xlsx
CAD - NVA - Financials (31.12.05 - 31.12.24).xlsx
CAD - PEY - Financials (31.12.05 - 31.12.24).xlsx
CAD - PKI - Financials (31.12.05 - 31.12.24).xlsx
CAD - POU - Financials (31.12.05 - 31.12.24).xlsx
CAD - TOU - Financials (31.12.09 - 31.12.24).xlsx
CAD - TRP - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000937 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000983 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002221 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002353 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 002423 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 600256 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600339 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600348 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600583 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600777 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601225 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 601666 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601699 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601872 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601918 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601975 - Financials (31.12.05 - 31.12.24).xlsx
COP - ECOPETROL - Financials (31.12.05 - 31.12.24).xlsx
EUR - ELPE - Financials (31.12.05 - 31.12.24).xlsx
EUR - ENI - Financials (31.12.05 - 31.12.24).xlsx
EUR - GALP - Financials (31.12.05 - 31.12.24).xlsx
EUR - MOH - Financials (31.12.05 - 31.12.24).xlsx
EUR - NESTE - Financials (31.12.05 - 31.12.24).xlsx
EUR - OMV - Financials (31.12.05 - 31.12.24).xlsx
EUR - REP - Financials (31.12.05 - 31.12.24).xlsx
EUR - SBMO - Financials (31.12.05 - 31.12.24).xlsx
EUR - SCR - Financials (31.12.05 - 31.12.24).xlsx
EUR - SPM - Financials (31.12.05 - 31.12.24).xlsx
EUR - SU - Financials (31.12.05 - 31.12.24).xlsx
EUR - TEN - Financials (31.12.05 - 31.12.24).xlsx
EUR - TTE - Financials (31.12.05 - 31.12.24).xlsx
EUR - VK - Financials (31.12.05 - 31.12.24).xlsx
EUR - VPK - Financials (31.12.05 - 31.12.24).xlsx
GBP - BP. - Financials (31.12.05 - 31.12.24).xlsx
GBP - SHEL - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1033 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1088 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1138 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1164 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1171 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1898 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 2380 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 386 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 857 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 883 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 956 - Financials (31.12.09 - 31.12.24).xlsx
IDR - ADRO - Financials (31.12.07 - 31.12.24).xlsx
IDR - BUMI - Financials (31.12.05 - 31.12.24).xlsx
IDR - BYAN - Financials (31.12.08 - 31.12.24).xlsx
IDR - DSSA - Financials (31.12.08 - 31.12.24).xlsx
ILS - DLEKG - Financials (31.12.05 - 31.12.24).xlsx
ILS - NWMD - Financials (31.12.05 - 31.12.24).xlsx
INR - AEGISLOG - Financials (31.3.06 - 31.3.25).xlsx
INR - COALINDIA - Financials (31.3.06 - 31.3.25).xlsx
INR - HINDPETRO - Financials (31.3.06 - 31.3.25).xlsx
INR - IOC - Financials (31.3.06 - 31.3.25).xlsx
INR - OIL - Financials (31.3.06 - 31.3.25).xlsx
INR - ONGC - Financials (31.3.06 - 31.3.25).xlsx
INR - PETRONET - Financials (31.3.06 - 31.3.25).xlsx
INR - RELIANCE - Financials (31.3.06 - 31.3.25).xlsx
JPY - 5019 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 5020 - Financials (31.3.09 - 31.3.25).xlsx
JPY - 6269 - Financials (31.12.05 - 31.12.24).xlsx
JPY - 8088 - Financials (31.3.06 - 31.3.25).xlsx
KRW - A010950 - Financials (31.12.07 - 31.12.24).xlsx
KRW - A096770 - Financials (31.12.07 - 31.12.24).xlsx
MYR - DIALOG - Financials (30.6.05 - 30.6.24).xlsx
MYR - PETDAG - Financials (31.3.06 - 31.12.24).xlsx
NOK - AKRBP - Financials (31.12.05 - 31.12.24).xlsx
NOK - EQNR - Financials (31.12.05 - 31.12.24).xlsx
NOK - SUBC - Financials (30.11.04 - 31.12.24).xlsx
PKR - MARI - Financials (30.6.09 - 30.6.24).xlsx
PKR - OGDC - Financials (30.6.06 - 30.6.24).xlsx
PLN - PKN - Financials (31.12.05 - 31.12.24).xlsx
QAR - QFLS - Financials (31.12.06 - 31.12.24).xlsx
SAR - 4030 - Financials (31.12.06 - 31.12.24).xlsx
THB - PTTEP - Financials (31.12.05 - 31.12.24).xlsx
THB - SCC - Financials (31.12.05 - 31.12.24).xlsx
USD - 900948 - Financials (31.12.05 - 31.12.24).xlsx
USD - APA - Financials (31.12.05 - 31.12.24).xlsx
USD - ARLP - Financials (31.12.05 - 31.12.24).xlsx
USD - AROC - Financials (31.12.05 - 31.12.24).xlsx
USD - CNX - Financials (31.12.05 - 31.12.24).xlsx
USD - COP - Financials (31.12.05 - 31.12.24).xlsx
USD - CQP - Financials (31.12.05 - 31.12.24).xlsx
USD - CRK - Financials (31.12.05 - 31.12.24).xlsx
USD - CTRA - Financials (31.12.05 - 31.12.24).xlsx
USD - CVI - Financials (31.12.05 - 31.12.24).xlsx
USD - CVX - Financials (31.12.05 - 31.12.24).xlsx
USD - DINO - Financials (31.12.05 - 31.12.24).xlsx
USD - DVN - Financials (31.12.05 - 31.12.24).xlsx
USD - EOG - Financials (31.12.05 - 31.12.24).xlsx
USD - EPD - Financials (31.12.05 - 31.12.24).xlsx
USD - EQT - Financials (31.12.05 - 31.12.24).xlsx
USD - ET - Financials (31.8.05 - 31.12.24).xlsx
USD - EXE - Financials (31.12.05 - 31.12.24).xlsx
USD - FANG - Financials (31.12.09 - 31.12.24).xlsx
USD - FRO - Financials (31.12.05 - 31.12.24).xlsx
USD - FTI - Financials (31.12.05 - 31.12.24).xlsx
USD - GEL - Financials (31.12.05 - 31.12.24).xlsx
USD - GLNG - Financials (31.12.05 - 31.12.24).xlsx
USD - GPOR - Financials (31.12.05 - 31.12.24).xlsx
USD - HAL - Financials (31.12.05 - 31.12.24).xlsx
USD - HES - Financials (31.12.05 - 31.12.24).xlsx
USD - KEY - Financials (31.12.05 - 31.12.24).xlsx
USD - LEU - Financials (31.12.05 - 31.12.24).xlsx
USD - LNG - Financials (31.12.05 - 31.12.24).xlsx
USD - MPC - Financials (31.12.08 - 31.12.24).xlsx
USD - MTDR - Financials (31.12.09 - 31.12.24).xlsx
USD - NOG - Financials (31.12.05 - 31.12.24).xlsx
USD - NOV - Financials (31.12.05 - 31.12.24).xlsx
USD - OKE - Financials (31.12.05 - 31.12.24).xlsx
USD - OVV - Financials (31.12.05 - 31.12.24).xlsx
USD - OXY - Financials (31.12.05 - 31.12.24).xlsx
USD - PAA - Financials (31.12.05 - 31.12.24).xlsx
USD - PBF - Financials (31.12.09 - 31.12.24).xlsx
USD - PPL - Financials (31.12.05 - 31.12.24).xlsx
USD - PSX - Financials (31.12.09 - 31.12.24).xlsx

USD - WFRD - Financials (31.12.05 - 31.12.24).xlsx
ZAR - EXX - Financials (31.12.05 - 31.12.24).xlsx
AED - ADCB - Financials (31.12.05 - 31.12.24).xlsx
AED - DFM - Financials (31.12.05 - 31.12.24).xlsx
AED - DIB - Financials (31.12.05 - 31.12.24).xlsx
AED - EMIRATESNBD - Financials (31.12.06 - 31.12.24).xlsx
AED - RAKBANK - Financials (31.12.06 - 31.12.24).xlsx
ARS - GGAL - Financials (31.12.05 - 31.12.24).xlsx
AUD - AFI - Financials (30.6.05 - 30.6.24).xlsx
AUD - ARG - Financials (30.6.02 - 30.6.24).xlsx
AUD - BOQ - Financials (31.8.05 - 31.8.24).xlsx
AUD - BPT - Financials (30.6.06 - 30.6.25).xlsx
AUD - MQG - Financials (31.3.03 - 31.3.25).xlsx
AUD - PNI - Financials (30.6.07 - 30.6.25).xlsx
AUD - QBE - Financials (31.12.02 - 31.12.24).xlsx
AUD - WBC - Financials (30.9.05 - 30.9.24).xlsx
BRL - BBAS3 - Financials (31.12.05 - 31.12.24).xlsx
BRL - ITSA4 - Financials (31.12.05 - 31.12.24).xlsx
BRL - PSSA3 - Financials (31.12.05 - 31.12.24).xlsx
CAD - BNS - Financials (31.10.05 - 31.10.24).xlsx
CAD - CM - Financials (31.10.05 - 31.10.24).xlsx
CAD - EQB - Financials (31.12.04 - 31.10.24).xlsx
CAD - L - Financials (31.12.05 - 31.12.24).xlsx
CAD - ONEX - Financials (31.12.05 - 31.12.24).xlsx
CAD - POW - Financials (31.12.05 - 31.12.24).xlsx
CAD - SLF - Financials (31.12.05 - 31.12.24).xlsx
CAD - U.UN - Financials (28.2.06 - 31.12.24).xlsx
CHF - ALLN - Financials (31.12.05 - 31.12.24).xlsx
CHF - BCGE - Financials (31.12.05 - 31.12.24).xlsx
CHF - BEKN - Financials (31.12.07 - 31.12.24).xlsx
CHF - CFR - Financials (31.3.06 - 31.3.25).xlsx
CHF - CMBN - Financials (31.12.07 - 31.12.24).xlsx
CHF - GRKP - Financials (31.12.05 - 31.12.24).xlsx
CHF - PGHN - Financials (31.12.05 - 31.12.24).xlsx
CHF - SLHN - Financials (31.12.05 - 31.12.24).xlsx
CHF - SPSN - Financials (31.12.05 - 31.12.24).xlsx
CHF - UBSG - Financials (31.12.05 - 31.12.24).xlsx
CHF - VAHN - Financials (31.12.05 - 31.12.24).xlsx
CHF - ZUGER - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000166 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000563 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000686 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000750 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000783 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000987 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 001227 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 002244 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002797 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002945 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 300059 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 600015 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600016 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600036 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600095 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600606 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600906 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600928 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601059 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 601099 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601128 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 601166 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601211 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601229 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601318 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601336 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 601519 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 601555 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601601 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601688 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 601696 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601818 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601838 - Financials (31.12.07 - 31.12.24).xlsx
COP - CIBEST - Financials (31.12.05 - 31.12.24).xlsx
COP - GRUPOSURA - Financials (31.12.07 - 31.12.24).xlsx
DKK - ALMB - Financials (31.12.05 - 31.12.24).xlsx
DKK - JYSK - Financials (31.12.05 - 31.12.24).xlsx
DKK - RILBA - Financials (31.12.05 - 31.12.24).xlsx
DKK - SPNO - Financials (31.12.05 - 31.12.24).xlsx
EUR - A5G - Financials (31.12.05 - 31.12.24).xlsx
EUR - ALV - Financials (31.12.05 - 31.12.24).xlsx
EUR - BAMI - Financials (31.12.05 - 31.12.24).xlsx
EUR - BCP - Financials (31.12.05 - 31.12.24).xlsx
EUR - BIRG - Financials (31.3.05 - 31.12.24).xlsx
EUR - BN - Financials (31.12.05 - 31.12.24).xlsx
EUR - BNP - Financials (31.12.05 - 31.12.24).xlsx
EUR - BPE - Financials (31.12.05 - 31.12.24).xlsx
EUR - BREB - Financials (31.12.05 - 31.12.24).xlsx
EUR - CAF - Financials (31.12.05 - 31.12.24).xlsx
EUR - CBK - Financials (31.12.05 - 31.12.24).xlsx
EUR - COFA - Financials (31.12.05 - 31.12.24).xlsx
EUR - DWNI - Financials (31.12.05 - 31.12.24).xlsx
EUR - EBS - Financials (31.12.05 - 31.12.24).xlsx
EUR - ETE - Financials (31.12.05 - 31.12.24).xlsx
EUR - EXO - Financials (31.12.05 - 31.12.24).xlsx
EUR - GYC - Financials (31.12.08 - 31.12.24).xlsx
EUR - HB - Financials (31.12.09 - 31.12.24).xlsx
EUR - LEG - Financials (31.12.08 - 31.12.24).xlsx
EUR - MAP - Financials (31.12.05 - 31.12.24).xlsx
EUR - MB - Financials (30.6.05 - 30.6.24).xlsx
EUR - MC - Financials (31.12.05 - 31.12.24).xlsx
EUR - OBS - Financials (31.12.05 - 31.12.24).xlsx
EUR - RBI - Financials (31.12.05 - 31.12.24).xlsx
EUR - SAB - Financials (31.12.05 - 31.12.24).xlsx
EUR - SAMPO - Financials (31.12.05 - 31.12.24).xlsx
EUR - SDF - Financials (31.12.05 - 31.12.24).xlsx
EUR - SOF - Financials (31.12.05 - 31.12.24).xlsx
EUR - TPEIR - Financials (31.12.05 - 31.12.24).xlsx
EUR - UCB - Financials (31.12.05 - 31.12.24).xlsx
EUR - ZABA - Financials (31.12.09 - 31.12.24).xlsx
GBP - ALW - Financials (31.1.05 - 31.12.24).xlsx
GBP - ATT - Financials (30.11.04 - 31.12.24).xlsx
GBP - BARC - Financials (31.12.05 - 31.12.24).xlsx
GBP - CNA - Financials (31.12.05 - 31.12.24).xlsx
GBP - EMG - Financials (31.3.05 - 31.12.24).xlsx
GBP - FCIT - Financials (31.12.05 - 31.12.24).xlsx
GBP - HICL - Financials (31.3.08 - 31.3.25).xlsx
GBP - ICG - Financials (31.3.06 - 31.3.25).xlsx
GBP - IWG - Financials (31.12.05 - 31.12.24).xlsx
GBP - JGGI - Financials (30.6.05 - 30.6.24).xlsx
GBP - MNKS - Financials (30.4.06 - 30.4.25).xlsx
GBP - PNL - Financials (30.4.06 - 30.4.25).xlsx
GBP - RAT - Financials (31.12.05 - 31.12.24).xlsx
GBP - RCP - Financials (31.3.05 - 31.12.24).xlsx
GBP - UTG - Financials (31.12.05 - 31.12.24).xlsx
HKD - 10 - Financials (30.6.05 - 31.12.24).xlsx
HKD - 11 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1109 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 123 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 1299 - Financials (30.11.09 - 31.12.24).xlsx
HKD - 1375 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 23 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 2328 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 3328 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 3618 - Financials (31.12.09 - 31.12.24).xlsx
HKD - 683 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 6881 - Financials (31.12.05 - 31.12.24).xlsx
HKD - 83 - Financials (30.6.05 - 30.6.24).xlsx
HKD - 939 - Financials (31.12.05 - 31.12.24).xlsx
HUF - MOL - Financials (31.12.05 - 31.12.24).xlsx
IDR - BBCA - Financials (31.12.06 - 31.12.24).xlsx
ILS - ALHE - Financials (31.12.05 - 31.12.24).xlsx
ILS - CLIS - Financials (31.12.04 - 31.12.24).xlsx
ILS - FIBI - Financials (31.12.05 - 31.12.24).xlsx
ILS - LUMI - Financials (31.12.05 - 31.12.24).xlsx
ILS - MMHD - Financials (31.12.05 - 31.12.24).xlsx
INR - 500302 - Financials (31.3.06 - 31.3.25).xlsx
INR - 500490 - Financials (31.3.06 - 31.3.25).xlsx
INR - 511218 - Financials (31.3.06 - 31.3.25).xlsx
INR - 533295 - Financials (31.3.07 - 31.3.25).xlsx
INR - BAJAJFINSV - Financials (31.3.08 - 31.3.25).xlsx
INR - BANKBARODA - Financials (31.3.06 - 31.3.25).xlsx
INR - CANBK - Financials (31.3.06 - 31.3.25).xlsx
INR - CENTRALBK - Financials (31.3.06 - 31.3.25).xlsx
INR - DLF - Financials (31.3.06 - 31.3.25).xlsx
INR - FEDERALBNK - Financials (31.3.06 - 31.3.25).xlsx
INR - HDFCBANK - Financials (31.3.06 - 31.3.25).xlsx
INR - ICICIBANK - Financials (31.3.06 - 31.3.25).xlsx
INR - IDBI - Financials (31.3.06 - 31.3.25).xlsx
INR - INDIANB - Financials (31.3.06 - 31.3.25).xlsx
INR - INDUSINDBK - Financials (31.3.06 - 31.3.25).xlsx
INR - KARURVYSYA - Financials (31.3.06 - 31.3.25).xlsx
INR - LICHSGFIN - Financials (31.3.06 - 31.3.25).xlsx
INR - M&MFIN - Financials (31.3.06 - 31.3.25).xlsx
INR - MFSL - Financials (31.3.06 - 31.3.25).xlsx
INR - MOTILALOFS - Financials (31.3.06 - 31.3.25).xlsx
INR - OBEROIRLTY - Financials (31.3.08 - 31.3.25).xlsx
INR - PFC - Financials (31.3.06 - 31.3.25).xlsx
INR - PNB - Financials (31.3.06 - 31.3.25).xlsx
INR - UCOBANK - Financials (31.3.06 - 31.3.25).xlsx
JPY - 1878 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 2801 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 3289 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8304 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8308 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8316 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8354 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8411 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8421 - Financials (31.3.08 - 31.3.25).xlsx
JPY - 8591 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8750 - Financials (31.3.06 - 31.3.25).xlsx
JPY - 8802 - Financials (31.3.06 - 31.3.25).xlsx
KRW - A016360 - Financials (31.3.07 - 31.12.24).xlsx
KRW - A029780 - Financials (31.12.07 - 31.12.24).xlsx
KRW - A032830 - Financials (31.3.07 - 31.12.24).xlsx
KRW - A039490 - Financials (31.3.07 - 31.12.24).xlsx
KRW - A086790 - Financials (31.12.07 - 31.12.24).xlsx
KWD - ABK - Financials (31.12.06 - 31.12.24).xlsx
KWD - BOUBYAN - Financials (31.12.06 - 31.12.24).xlsx
KWD - BURG - Financials (31.12.06 - 31.12.24).xlsx
KWD - KFH - Financials (31.12.06 - 31.12.24).xlsx
KWD - MABANEE - Financials (31.12.06 - 31.12.24).xlsx
MXN - ELEKTRA _ - Financials (31.12.05 - 31.12.24).xlsx
MXN - Q _ - Financials (31.12.08 - 31.12.24).xlsx
MYR - AMBANK - Financials (31.3.06 - 31.3.25).xlsx
MYR - PBBANK - Financials (31.12.05 - 31.12.24).xlsx
NOK - MING - Financials (31.12.05 - 31.12.24).xlsx
NOK - OLT - Financials (31.12.05 - 31.12.24).xlsx
NOK - SB1NO - Financials (31.12.05 - 31.12.24).xlsx
PEN - BBVAC1 - Financials (31.12.05 - 31.12.24).xlsx
PEN - CREDITC1 - Financials (31.12.05 - 31.12.24).xlsx
PHP - ALI - Financials (31.12.05 - 31.12.24).xlsx
PHP - BPI - Financials (31.12.05 - 31.12.24).xlsx
PHP - SMPH - Financials (31.12.05 - 31.12.24).xlsx
PLN - KRU - Financials (31.12.05 - 31.12.24).xlsx
PLN - PKO - Financials (31.12.05 - 31.12.24).xlsx
PLN - SPL - Financials (31.12.05 - 31.12.24).xlsx
PLN - TPE - Financials (31.12.09 - 31.12.24).xlsx
QAR - BRES - Financials (31.12.06 - 31.12.24).xlsx
QAR - ERES - Financials (31.12.06 - 31.12.24).xlsx
QAR - MARK - Financials (31.12.06 - 31.12.24).xlsx
QAR - QIBK - Financials (31.12.05 - 31.12.24).xlsx
QAR - QIIK - Financials (31.12.06 - 31.12.24).xlsx
RON - TLV - Financials (31.12.08 - 31.12.24).xlsx
SAR - 1050 - Financials (31.12.06 - 31.12.24).xlsx
SAR - 1060 - Financials (31.12.06 - 31.12.24).xlsx
SAR - 1080 - Financials (31.12.06 - 31.12.24).xlsx
SAR - 1150 - Financials (31.12.08 - 31.12.24).xlsx
SAR - 4150 - Financials (31.12.06 - 31.12.24).xlsx
SEK - AZA - Financials (31.12.05 - 31.12.24).xlsx
SEK - CAST - Financials (31.12.05 - 31.12.24).xlsx
SEK - HUFV A - Financials (31.12.05 - 31.12.24).xlsx
SEK - INVE A - Financials (31.12.05 - 31.12.24).xlsx
SEK - KINV B - Financials (31.12.05 - 31.12.24).xlsx
SEK - LUND B - Financials (31.12.05 - 31.12.24).xlsx
SEK - SAGA A - Financials (31.12.06 - 31.12.24).xlsx
THB - BAY - Financials (31.12.05 - 31.12.24).xlsx
THB - BTS - Financials (31.3.06 - 31.3.25).xlsx
THB - SCB - Financials (31.12.05 - 31.12.24).xlsx
THB - TISCO - Financials (31.12.05 - 31.12.24).xlsx
USD - AB - Financials (31.12.05 - 31.12.24).xlsx
USD - ABG - Financials (31.12.05 - 31.12.24).xlsx
USD - ACGL - Financials (31.12.05 - 31.12.24).xlsx
USD - ADM - Financials (30.6.05 - 31.12.24).xlsx
USD - AGM - Financials (31.12.05 - 31.12.24).xlsx
USD - AGNC - Financials (31.12.08 - 31.12.24).xlsx
USD - AGO - Financials (31.12.05 - 31.12.24).xlsx
USD - AIZ - Financials (31.12.05 - 31.12.24).xlsx
USD - AJG - Financials (31.12.05 - 31.12.24).xlsx
USD - AMP - Financials (31.12.05 - 31.12.24).xlsx
USD - APAM - Financials (31.12.09 - 31.12.24).xlsx
USD - ARCC - Financials (31.12.05 - 31.12.24).xlsx
USD - ASB - Financials (31.12.05 - 31.12.24).xlsx
USD - AUB - Financials (31.12.05 - 31.12.24).xlsx
USD - AX - Financials (30.6.06 - 30.6.25).xlsx
USD - BAP - Financials (31.12.05 - 31.12.24).xlsx
USD - BEN - Financials (30.9.05 - 30.9.24).xlsx
USD - BKU - Financials (31.12.09 - 31.12.24).xlsx
USD - BOH - Financials (31.12.05 - 31.12.24).xlsx
USD - BRK.A - Financials (31.12.05 - 31.12.24).xlsx
USD - BRO - Financials (31.12.05 - 31.12.24).xlsx
USD - BXMT - Financials (31.12.05 - 31.12.24).xlsx
USD - CB - Financials (31.12.05 - 31.12.24).xlsx
USD - CBRE - Financials (31.12.05 - 31.12.24).xlsx
USD - CBU - Financials (31.12.05 - 31.12.24).xlsx
USD - CME - Financials (31.12.05 - 31.12.24).xlsx
USD - CPAY - Financials (31.12.08 - 31.12.24).xlsx
USD - EFSC - Financials (31.12.05 - 31.12.24).xlsx
USD - EG - Financials (31.12.05 - 31.12.24).xlsx
USD - ENVA - Financials (31.12.09 - 31.12.24).xlsx
USD - EWBC - Financials (31.12.05 - 31.12.24).xlsx
USD - FCFS - Financials (31.12.05 - 31.12.24).xlsx
USD - FCNC.A - Financials (31.12.05 - 31.12.24).xlsx
USD - FFBC - Financials (31.12.05 - 31.12.24).xlsx
USD - FHI - Financials (31.12.05 - 31.12.24).xlsx
USD - FI - Financials (31.12.05 - 31.12.24).xlsx
USD - FNMA - Financials (31.12.05 - 31.12.24).xlsx
USD - GBDC - Financials (30.9.09 - 30.9.24).xlsx
USD - GLXY - Financials (31.12.05 - 31.12.24).xlsx
USD - HAL - Financials (31.12.05 - 31.12.24).xlsx
USD - HHH - Financials (31.12.09 - 31.12.24).xlsx
USD - HTGC - Financials (31.12.05 - 31.12.24).xlsx
USD - IBKR - Financials (31.12.05 - 31.12.24).xlsx
USD - ICE - Financials (31.12.05 - 31.12.24).xlsx
USD - IFS - Financials (31.12.06 - 31.12.24).xlsx
USD - JEF - Financials (31.12.04 - 30.11.24).xlsx
USD - JHG - Financials (31.12.05 - 31.12.24).xlsx
USD - JKHY - Financials (30.6.05 - 30.6.24).xlsx
USD - JLL - Financials (31.12.05 - 31.12.24).xlsx
USD - KMPR - Financials (31.12.05 - 31.12.24).xlsx
USD - LAZ - Financials (31.12.05 - 31.12.24).xlsx
USD - LPLA - Financials (31.12.05 - 31.12.24).xlsx
USD - MKL - Financials (31.12.05 - 31.12.24).xlsx
USD - MORN - Financials (31.12.05 - 31.12.24).xlsx
USD - MRC - Financials (31.12.09 - 31.12.24).xlsx
USD - MS - Financials (30.11.05 - 31.12.24).xlsx
USD - NTRS - Financials (31.12.05 - 31.12.24).xlsx
USD - NWL - Financials (31.12.05 - 31.12.24).xlsx
USD - PNFP - Financials (31.12.05 - 31.12.24).xlsx
USD - PPBI - Financials (31.12.05 - 31.12.24).xlsx
USD - PRI - Financials (31.12.07 - 31.12.24).xlsx
USD - PRU - Financials (31.12.05 - 31.12.24).xlsx
USD - PSA - Financials (31.12.05 - 31.12.24).xlsx
USD - RDN - Financials (31.12.05 - 31.12.24).xlsx
USD - RF - Financials (31.12.05 - 31.12.24).xlsx
USD - RGA - Financials (31.12.05 - 31.12.24).xlsx
USD - RJF - Financials (30.9.05 - 30.9.24).xlsx
USD - RLI - Financials (31.12.05 - 31.12.24).xlsx
USD - RNR - Financials (31.12.05 - 31.12.24).xlsx
USD - RNST - Financials (31.12.05 - 31.12.24).xlsx
USD - SBCF - Financials (31.12.05 - 31.12.24).xlsx
USD - SCHW - Financials (31.12.05 - 31.12.24).xlsx
USD - SEIC - Financials (31.12.05 - 31.12.24).xlsx
USD - SFBS - Financials (31.12.09 - 31.12.24).xlsx
USD - SLM - Financials (31.12.05 - 31.12.24).xlsx
USD - SSB - Financials (31.12.05 - 31.12.24).xlsx
USD - STT - Financials (31.12.05 - 31.12.24).xlsx
USD - STWD - Financials (31.12.09 - 31.12.24).xlsx
USD - TOWN - Financials (31.12.05 - 31.12.24).xlsx
USD - TRMK - Financials (31.12.05 - 31.12.24).xlsx
USD - UMBF - Financials (31.12.05 - 31.12.24).xlsx
USD - WAFD - Financials (30.9.05 - 30.9.24).xlsx
USD - WBS - Financials (31.12.05 - 31.12.24).xlsx
USD - WD - Financials (31.12.08 - 31.12.24).xlsx
USD - WEX - Financials (31.12.05 - 31.12.24).xlsx
USD - WSFS - Financials (31.12.05 - 31.12.24).xlsx
USD - WTFC - Financials (31.12.05 - 31.12.24).xlsx
USD - WTW - Financials (31.12.05 - 31.12.24).xlsx
USD - ZG - Financials (31.12.09 - 31.12.24).xlsx
VND - ACB - Financials (31.12.09 - 31.12.24).xlsx
VND - SHB - Financials (31.12.08 - 31.12.24).xlsx
VND - STB - Financials (31.12.08 - 31.12.24).xlsx
VND - VCB - Financials (31.12.08 - 31.12.24).xlsx
VND - VIC - Financials (31.12.08 - 31.12.24).xlsx
ZAR - CPI - Financials (28.2.06 - 28.2.25).xlsx
ZAR - NED - Financials (31.12.05 - 31.12.24).xlsx
ZAR - OMU - Financials (31.12.05 - 31.12.24).xlsx
AUD - CPU - Financials (30.6.05 - 30.6.24).xlsx
AUD - HVN - Financials (30.6.04 - 30.6.24).xlsx
AUD - QUB - Financials (30.6.08 - 30.6.24).xlsx
AUD - SGH - Financials (30.6.04 - 30.6.24).xlsx
AUD - SUN - Financials (30.6.05 - 30.6.24).xlsx
AUD - WOR - Financials (30.6.05 - 30.6.24).xlsx
BRL - MOTV3 - Financials (31.12.05 - 31.12.24).xlsx
CAD - ATRL - Financials (31.12.05 - 31.12.24).xlsx
CAD - ATS - Financials (31.3.06 - 31.3.25).xlsx
CAD - BB - Financials (28.2.06 - 28.2.25).xlsx
CAD - CAE - Financials (31.3.06 - 31.3.25).xlsx
CAD - FTT - Financials (31.12.05 - 31.12.24).xlsx
CHF - ADEN - Financials (31.12.05 - 31.12.24).xlsx
CHF - BCHN - Financials (31.3.06 - 31.3.25).xlsx
CHF - BUCN - Financials (31.12.05 - 31.12.24).xlsx
CHF - DAE - Financials (31.12.05 - 31.12.24).xlsx
CHF - DOKA - Financials (30.6.05 - 30.6.24).xlsx
CHF - FHZN - Financials (31.12.05 - 31.12.24).xlsx
CHF - SCHN - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000088 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000157 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000425 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000519 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000528 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000738 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000768 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 000800 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002028 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002074 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002130 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002202 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 002335 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 002340 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 002372 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 002468 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 002625 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 002690 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 300014 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 300070 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 300124 - Financials (31.12.07 - 31.12.24).xlsx
CNY - 300276 - Financials (31.12.08 - 31.12.24).xlsx
CNY - 600009 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600039 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600221 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600233 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600312 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600320 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600388 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600416 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600428 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600435 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600482 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600516 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600517 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600522 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600528 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600577 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600582 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600720 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600764 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600862 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600885 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 600893 - Financials (31.12.05 - 31.12.24).xlsx
CNY - 601018 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 601106 - Financials (31.12.06 - 31.12.24).xlsx
CNY - 601390 - Financials (31.12.05 - 31.12.24).xlsx

In [ ]:
# parallel_utils.py
from __future__ import annotations
from typing import Iterable, Callable, TypeVar, Generic, Any, Union, List
from joblib import Parallel, delayed

T = TypeVar("T")
R = TypeVar("R")

def parallel_map(
    items: Iterable[T],
    func: Callable[[T], R],
    *,
    n_jobs: int = -1,                 # -1 = todos los cores
    prefer: str = "threads",          # "threads" (I/O) | "processes" (CPU)
    batch_size: Union[int, str, None] = "auto",
    progress: bool = True,
    on_error: str = "raise",          # "raise" | "return"
) -> List[R]:
    """
    Aplica func(item) en paralelo sobre 'items' usando joblib.
    - on_error="raise": la primera excepción detiene todo.
      on_error="return": devuelve la excepción en el lugar del resultado.
    - progress=True: intenta mostrar barra de progreso con tqdm (si está instalado).
    """
    it = list(items)
    if progress:
        try:
            from tqdm.auto import tqdm  # opcional
            it = tqdm(it, desc="Processing", unit="task")
        except Exception:
            pass

    def _safe(item: T) -> R:
        try:
            return func(item)
        except Exception as e:               # type: ignore[return-value]
            if on_error == "raise":
                raise
            return e                         # devuelve la excepción como resultado

    results: List[R] = Parallel(n_jobs=n_jobs, prefer=prefer, batch_size=batch_size)(
        delayed(_safe)(x) for x in it
    )
    return results

In [ ]:
import json

with open("C:/TFM/tfm_env/data/01_raw/01.3.2 AllTickersInfo/" + "AllTickersInfo.json", "r") as file:
    all_ticker_info = json.load(file)

inv_all_ticker_info = {sector: {v: k for k, v in all_ticker_info[sector].items()} for sector in all_ticker_info.keys()}

In [ ]:
import logging

# Configuración básica del logger
logging.basicConfig(
    filename="C:/TFM/tfm_env/data/02_intermediate/02.2.3 SeleccionHistoricoEstadosFinancierosUnificadosTodosLosSectores/logs/app.log",              # Nombre del archivo de logs
    level=logging.INFO,              # Nivel mínimo (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    format="%(asctime)s - %(levelname)s - %(message)s"  # Formato del log
)

# # Ejemplo de uso
# logging.debug("Esto es un mensaje DEBUG (no se guardará porque el nivel está en INFO).")
# logging.info("Inicio de la aplicación")
# logging.warning("Cuidado, algo no va del todo bien...")
# logging.error("Ha ocurrido un error")
# logging.critical("Error crítico, se debe detener el programa")

In [456]:
from datetime import datetime

logging.info("Inicio del programa.\n")

statement_data_dir = "data/01_raw/01.3 - HistoricoEstadosFinancieros/"
statement_data_dir_dest = "data/02_intermediate/02.1 - HistoricoEstadosFinancieros/"
selected_data_dir_dest = "data/02_intermediate/02.2 - SeleccionHistoricoEstadosFinancieros/"
sheets = ["Income Statement", "Ratios", "Cash Flow"]

sectors = [dir + "/" for dir in os.listdir(statement_data_dir)]

dataframe = pd.DataFrame()

dataframe["Sector"] = []
dataframe["% Free Cash Flow Margins"] = []




for r in ratios_list:

    dataframe[r] = []

h = True
for sector in sectors[:-1]: # Al final, eliminar los corchetes y dejar como lista. Ahora fijamos solo ConsumoDiscrecional
    for file in os.listdir(statement_data_dir + sector):
        # logging.info(f"Entrando en ", statement_data_dir + sectors[1])
        
        valid_cash_flow_file = False
        valid_ratio_file = False
        valid_income_statement_file = False
        for sheet in sheets:
            # logging.info(f"Leyendo hoja: {sheet}")
            
            df = pl.read_excel(f"{statement_data_dir}{sector}{file}", sheet_name=sheet)


            if sheet == "Income Statement":
                income_statement_dataframe = df.to_pandas()
                title_idx_income_statement = sheet + " | TIKR.com"

                l = income_statement_dataframe.keys().tolist()
                l.remove(sheet + " | TIKR.com")
                l.remove("LTM")
                l = [datetime.strptime(d, "%d/%m/%y") for d in l]
                if (max(l).year<2024) or (len(l)<16):
                    continue
                
                valid_income_statement_file = is_valid_file_income_statement(income_statement_dataframe, ["Total Revenues"])
                


            if sheet == "Cash Flow":
                cash_flow_dataframe = df.to_pandas()
                title_idx_cash_flow = sheet + " | TIKR.com"

                l = cash_flow_dataframe.keys().tolist()
                l.remove(sheet + " | TIKR.com")
                l.remove("LTM")
                l = [datetime.strptime(d, "%d/%m/%y") for d in l]
                if (max(l).year<2024) or (len(l)<16):
                    continue
                
                valid_cash_flow_file = is_valid_file_cash_flow(cash_flow_dataframe, ["% Free Cash Flow Margins"])
                
            if sheet == "Ratios":
                ratios_dataframe = df.to_pandas()
                title_idx_ratio = sheet + " | TIKR.com"
                l = ratios_dataframe.keys().tolist()
                l.remove(title_idx_ratio)
                l.remove("LTM")
                l = [datetime.strptime(d, "%d/%m/%y") for d in l]
                if (max(l).year<2024) or (len(l)<16):
                    continue
                
                valid_ratio_file = is_valid_file_ratio(ratios_dataframe, ratios_list)


        if (valid_cash_flow_file and valid_ratio_file) and valid_income_statement_file:
            
            
            i = income_statement_dataframe.set_index(title_idx_income_statement)
            i_cols=i.keys().tolist()
            i_cols.remove("LTM")
            i_serie = i[i_cols].transpose()["Total Revenues"]
            
            
            c = cash_flow_dataframe.set_index(title_idx_cash_flow, )

            c_cols = c.keys().tolist()
            c_cols.remove("LTM")
            fcf_serie = c[c_cols].transpose()["% Free Cash Flow Margins"]


            r = ratios_dataframe.set_index(title_idx_ratio)

            r_cols = r.keys().tolist()
            r_cols.remove("LTM")

            r_df = r[r_cols].transpose()[ratios_list]

            data = pd.concat([r_df, fcf_serie, i_serie], axis=1)
            
            
            ticker_name = extract_tikr(file)
            statement_currency = extract_currency(file)
            data["statement currency"] = statement_currency
            data["ticker"] = ticker_name
            data["sector"] = sector[:-1]
            data.reset_index(inplace=True)
            data = data.rename(columns={"index": "Date"})
            
            
            ticker = all_ticker_info[sector[:-1]][ticker_name]
            historical_price_company_dir="data/01_raw/01.4 - DatosHistoricosPrecios/Empresas/"
            hist_df =None
            
            for file_historical_price in os.listdir(historical_price_company_dir):
                if file_historical_price.split("_")[0] == ticker:
                    hist_df = pd.read_csv(f"{historical_price_company_dir}{file_historical_price}", header=[0, 1, 2])
                    close_currency = file_historical_price.split("_")[1].replace(".csv", "")
                    break
            
            if hist_df is None:
                continue
            
            data["Date"] = data.Date.apply(lambda x: pd.to_datetime(x, utc=True))
            data["year"] = data.Date.apply(lambda x: x.year)

            C = hist_df["Close"].transpose().reset_index().transpose().iloc[2:]
            C.rename(columns={0: "Close"}, inplace=True)
            C["Date"] = hist_df["Price"]["Ticker"]["Date"]
            C["Date"] = C.Date.apply(lambda x: pd.to_datetime(x, utc=True))
            C["year"] = C.Date.apply(lambda x: x.year)
            C["close currency"] = close_currency
            C = C.set_index("Date").join(data[data.ticker==ticker_name].set_index("year"), on="year", how="left", lsuffix="l_", rsuffix="r_")
            
            data.set_index("Date")
            
            
            
            
            data.to_csv(f"{selected_data_dir_dest}{ticker_name}-data.csv", index_label="Date")
            data.to_csv(f"data/02_intermediate/02.2.3 SeleccionHistoricoEstadosFinancierosUnificadosTodosLosSectores/AllData.csv", mode="a", index_label="Date", header=h)
            C.to_csv(f"data/02_intermediate/02.2.3 SeleccionHistoricoEstadosFinancierosUnificadosTodosLosSectores/AllDataClosePrices.csv", mode="a", index_label="Date", header=h)
            h = False
            
            for sheet in sheets:

                df = pl.read_excel(f"{statement_data_dir}{sector}{file}", sheet_name=sheet)
                nombre_csv = f"{statement_data_dir_dest}{sector}{file[:-5]}-{sheet}.csv"
                # logging.info(nombre_csv)
                df.write_csv(nombre_csv)
                logging.info(f"Guardado: {nombre_csv}")
                
            

logging.info("El script finalizó.\n")

In [451]:
inv_all_ticker_info

{'BienesRaíces': {'CHC.AX': 'CHC',
  'GPT.AX': 'GPT',
  'MGR.AX': 'MGR',
  'SGP.AX': 'SGP',
  'HR-UN.TO': 'HR.UN',
  'COV.PA': 'COV',
  'ICAD.PA': 'ICAD',
  'MRL.MC': 'MRL',
  'BLND.L': 'BLND',
  'LAND.L': 'LAND',
  '3279.T': '3279',
  '3309.T': '3309',
  '3462.T': '3462',
  '8960.T': '8960',
  '8972.T': '8972',
  '8984.T': '8984',
  'DANHOS13.MX': 'DANHOS 13',
  'FUNO11.MX': 'FUNO 11',
  'KLCC.KL': 'KLCC',
  'N2IU.SI': 'N2IU',
  'T82U.SI': 'T82U',
  'ZRGYO.IS': 'ZRGYO',
  'BNL': 'BNL',
  'EPRT': 'EPRT',
  'ESBA': 'ESBA',
  'LMT': 'LMT',
  'WPC': 'WPC',
  'GRT.JO': 'GRT'},
 'ConsumoDiscrecional': {'TALABAT.AE': 'TALABAT',
  'BRG.AX': 'BRG',
  'PMV.AX': 'PMV',
  'SMFT3.SA': 'SMFT3',
  'VBBR3.SA': 'VBBR3',
  'DOL.TO': 'DOL',
  'HBM.TO': 'HBM',
  'MG.TO': 'MG',
  'AVOL.SW': 'AVOL',
  'UHR.SW': 'UHR',
  'COPEC.SN': 'COPEC',
  '000559.SZ': '000559',
  '000564.SZ': '000564',
  '000625.SZ': '000625',
  '000887.SZ': '000887',
  '002031.SZ': '002031',
  '002032.SZ': '002032',
  '002085.SZ': '002085',
  '002472.SZ': '002472',
  '002850.SZ': '002850',
  '300979.SZ': '300979',
  '600690.SS': '600690',
  '600699.SS': '600699',
  '600839.SS': '600839',
  '600859.SS': '600859',
  '600933.SS': '600933',
  '601777.SS': '601777',
  '601799.SS': '601799',
  '601888.SS': '601888',
  '603129.SS': '603129',
  '603486.SS': '603486',
  '603786.SS': '603786',
  '688169.SS': '688169',
  '688819.SS': '688819',
  '689009.SS': '689009',
  'GN.CO': 'GN',
  'ADS.DE': 'ADS',
  'AMS.MC': 'AMS',
  'BAIN.MI': 'BAIN',
  'BELA.BR': 'BELA',
  'BRE.MI': 'BRE',
  'CDI.PA': 'CDI',
  'DIE.BR': 'DIE',
  'ITX.MC': 'ITX',
  'KER.PA': 'KER',
  'ML.PA': 'ML',
  'PETG.DE': 'PETG',
  'PIRC.MI': 'PIRC',
  'PRX.AS': 'PRX',
  'RACE.MI': 'RACE',
  'RNO.PA': 'RNO',
  'SHA.DE': 'SHA0',
  'SK.PA': 'SK',
  'STLAM.MI': 'STLAM',
  'TUI1.DE': 'TUI1',
  'ZAL.DE': 'ZAL',
  'ZO1.DE': 'ZO1',
  'BRBY.L': 'BRBY',
  'BTRW.L': 'BTRW',
  'DNLM.L': 'DNLM',
  'ENT.L': 'ENT',
  'FRAS.L': 'FRAS',
  'TW.L': 'TW.',
  'WTB.L': 'WTB',
  '1070.HK': '1070',
  '1128.HK': '1128',
  '1364.HK': '1364',
  '0175.HK': '175',
  '1999.HK': '1999',
  '2097.HK': '2097',
  '2333.HK': '2333',
  '0027.HK': '27',
  '6181.HK': '6181',
  '0780.HK': '780',
  '9992.HK': '9992',
  'BELI.JK': 'BELI',
  '500086.BO': '500086',
  '500182.BO': '500182',
  '500238.BO': '500238',
  '500251.BO': '500251',
  '502355.BO': '502355',
  '505200.BO': '505200',
  '521238.BO': '521238',
  'BAJAJ-AUTO.NS': 'BAJAJ',
  'ENDURANCE.NS': 'ENDURANCE',
  'ETERNAL.NS': 'ETERNAL',
  'HYUNDAI.BO': 'HYUNDAI',
  'JUBLFOOD.NS': 'JUBLFOOD',
  'KALYANKJIL.NS': 'KALYANKJIL',
  'METROBRAND.NS': 'METROBRAND',
  'MRF.NS': 'MRF',
  'MSUMI.NS': 'MSUMI',
  'SUNDRMFAST.NS': 'SUNDRMFAST',
  'TIINDIA.NS': 'TIINDIA',
  '2282.T': '2282',
  '2726.T': '2726',
  '3086.T': '3086',
  '3099.T': '3099',
  '3116.T': '3116',
  '3350.T': '3350',
  '3397.T': '3397',
  '4732.T': '4732',
  '4755.T': '4755',
  '5101.T': '5101',
  '5108.T': '5108',
  '5947.T': '5947',
  '6460.T': '6460',
  '6755.T': '6755',
  '6758.T': '6758',
  '6923.T': '6923',
  '7203.T': '7203',
  '7211.T': '7211',
  '7269.T': '7269',
  '7270.T': '7270',
  '7272.T': '7272',
  '7282.T': '7282',
  '7453.T': '7453',
  '7550.T': '7550',
  '7832.T': '7832',
  '7936.T': '7936',
  '7951.T': '7951',
  '8227.T': '8227',
  '8233.T': '8233',
  '180640.KS': 'A180640',
  '257720.KS': 'A257720',
  'LIVEPOLC-1.MX': 'LIVEPOL C',
  'GENM.KL': 'GENM',
  'GENTING.KL': 'GENTING',
  'ALE.WA': 'ALE',
  'LPP.WA': 'LPP',
  'ASMDEE-B.ST': 'ASMDEE B',
  'BETS-B.ST': 'BETS B',
  'CLAS-B.ST': 'CLAS B',
  'THULE.ST': 'THULE',
  'G13.SI': 'G13',
  'TOASO.IS': 'TOASO',
  '1476.TW': '1476',
  '2258.TW': '2258',
  '6890.TW': '6890',
  '8111.TW': '8111',
  '8114.TW': '8114',
  '9904.TW': '9904',
  '9910.TW': '9910',
  'BCAUY': '1114',
  '601965.SS': '601965',
  '603596.SS': '603596',
  'ALL': 'ALL',
  'AMZN': 'AMZN',
  'ANF': 'ANF',
  'APTV': 'APTV',
  'AZO': 'AZO',
  'BBWI': 'BBWI',
  'BBY': 'BBY',
  'BIRK': 'BIRK',
  'BWA': 'BWA',
  'CAKE': 'CAKE',
  'CAVA': 'CAVA',
  'CCL': 'CCL',
  'CMG': 'CMG',
  'CRC': 'CRC',
  'CROX': 'CROX',
  'CVCO': 'CVCO',
  'CZR': 'CZR',
  'DDS': 'DDS',
  'DRI': 'DRI',
  'EAT': 'EAT',
  'ETSY': 'ETSY',
  'EVO': 'EVO',
  'FL': 'FL',
  'FLUT': 'FLUT',
  'FND': 'FND',
  'FTDR': 'FTDR',
  'GPS': 'GAP',
  'GENI': 'GENI',
  'GLBE': 'GLBE',
  'GME': 'GME',
  'GNTX': 'GNTX',
  'GRMN': 'GRMN',
  'GTX': 'GTX',
  'H': 'H',
  'HD': 'HD',
  'HGV': 'HGV',
  'JD': 'JD',
  'KBH': 'KBH',
  'KMX': 'KMX',
  'LCID': 'LCID',
  'LCII': 'LCII',
  'LEA': 'LEA',
  'LEN': 'LEN',
  'LI': 'LI',
  'LKQ': 'LKQ',
  'LTH': 'LTH',
  'LULU': 'LULU',
  'LVS': 'LVS',
  'MAR': 'MAR',
  'MCD': 'MCD',
  'MNSO': 'MNSO',
  'MOD': 'MOD',
  'MRP': 'MRP',
  'MUSA': 'MUSA',
  'NKE': 'NKE',
  'ONON': 'ONON',
  'OSW': 'OSW',
  'PATK': 'PATK',
  'PLUS': 'PLUS',
  'PRDO': 'PRDO',
  'SBUX': 'SBUX',
  'SGI': 'SGI',
  'SN': 'SN',
  'STRA': 'STRA',
  'SW': 'SW',
  'TCOM': 'TCOM',
  'TMHC': 'TMHC',
  'TOL': 'TOL',
  'TSCO': 'TSCO',
  'ULTA': 'ULTA',
  'VFC': 'VFC',
  'VIK': 'VIK',
  'W': 'W',
  'WING': 'WING',
  'WYNN': 'WYNN',
  'XPEV': 'XPEV',
  'YETI': 'YETI',
  'ZGN': 'ZGN',
  'TFG.JO': 'TFG',
  'WHL.JO': 'WHL'},
 'Energía': {'TGSU2.BA': 'TGSU2',
  'YPFD.BA': 'YPFD',
  'ALD.AX': 'ALD',
  'INA.AX': 'INA',
  'NHC.AX': 'NHC',
  'STO.AX': 'STO',
  'WDS.AX': 'WDS',
  'WHC.AX': 'WHC',
  'CSAN3.SA': 'CSAN3',
  'PETR4.SA': 'PETR4',
  'PRIO3.SA': 'PRIO3',
  'ATH.TO': 'ATH',
  'CCO.TO': 'CCO',
  'CNQ.TO': 'CNQ',
  'CNR.TO': 'CNR',
  'CVE.TO': 'CVE',
  'ENB.TO': 'ENB',
  'IMO.TO': 'IMO',
  'NVA.TO': 'NVA',
  'PEY.TO': 'PEY',
  'PKI.TO': 'PKI',
  'POU.TO': 'POU',
  'TOU.TO': 'TOU',
  'TRP.TO': 'TRP',
  '000937.SZ': '000937',
  '000983.SZ': '000983',
  '002221.SZ': '002221',
  '002353.SZ': '002353',
  '002423.SZ': '002423',
  '600256.SS': '600256',
  '600339.SS': '600339',
  '600348.SS': '600348',
  '600583.SS': '600583',
  '600777.SS': '600777',
  '601225.SS': '601225',
  '601666.SS': '601666',
  '601699.SS': '601699',
  '601872.SS': '601872',
  '601918.SS': '601918',
  '601975.SS': '601975',
  'ECOPETROL.CO': 'ECOPETROL',
  'ELPE.AT': 'ELPE',
  'ENI.MI': 'ENI',
  'GALP.LS': 'GALP',
  'MOH.AT': 'MOH',
  'NESTE.HE': 'NESTE',
  'OMV.VI': 'OMV',
  'REP.MC': 'REP',
  'SBMO.AS': 'SBMO',
  'SCR.PA': 'SCR',
  'SPM.MI': 'SPM',
  'SU.PA': 'SU',
  'TEN.MI': 'TEN',
  'TTE.PA': 'TTE',
  'VK.PA': 'VK',
  'VPK.AS': 'VPK',
  'BP.L': 'BP.',
  'SHEL.L': 'SHEL',
  '1033.HK': '1033',
  '1088.HK': '1088',
  '1138.HK': '1138',
  '1164.HK': '1164',
  '1171.HK': '1171',
  '1898.HK': '1898',
  '2380.HK': '2380',
  '0386.HK': '386',
  '0857.HK': '857',
  '0883.HK': '883',
  '0956.HK': '956',
  'ADRO.JK': 'ADRO',
  'BUMI.JK': 'BUMI',
  'BYAN.JK': 'BYAN',
  'DSSA.JK': 'DSSA',
  'DLEKG.TA': 'DLEKG',
  'NWMD.TA': 'NWMD',
  'AEGISLOG.NS': 'AEGISLOG',
  'COALINDIA.NS': 'COALINDIA',
  'HINDPETRO.NS': 'HINDPETRO',
  'IOC.NS': 'IOC',
  'OIL.NS': 'OIL',
  'ONGC.NS': 'ONGC',
  'PETRONET.NS': 'PETRONET',
  'RELIANCE.NS': 'RELIANCE',
  '5019.T': '5019',
  '5020.T': '5020',
  '6269.T': '6269',
  '8088.T': '8088',
  '010950.KS': 'A010950',
  '096770.KS': 'A096770',
  'DIALOG.KL': 'DIALOG',
  'PETDAG.KL': 'PETDAG',
  'AKRBP.OL': 'AKRBP',
  'EQNR.OL': 'EQNR',
  'SUBC.OL': 'SUBC',
  'MARI.PSX': 'MARI',
  'OGDC.PSX': 'OGDC',
  'PKN.WA': 'PKN',
  'QFLS.QA': 'QFLS',
  '4030.SR': '4030',
  'PTTEP.BK': 'PTTEP',
  'SCC.BK': 'SCC',
  '900948.SS': '900948',
  'APA': 'APA',
  'ARLP': 'ARLP',
  'AROC': 'AROC',
  'CNX': 'CNX',
  'COP': 'COP',
  'CQP': 'CQP',
  'CRK': 'CRK',
  'CTRA': 'CTRA',
  'CVI': 'CVI',
  'CVX': 'CVX',
  'DINO': 'DINO',
  'DVN': 'DVN',
  'EOG': 'EOG',
  'EPD': 'EPD',
  'EQT': 'EQT',
  'ET': 'ET',
  'EXE': 'EXE',
  'FANG': 'FANG',
  'FRO': 'FRO',
  'FTI': 'FTI',
  'GEL': 'GEL',
  'GLNG': 'GLNG',
  'GPOR': 'GPOR',
  'HAL': 'HAL',
  'HES': 'HES',
  'KEY': 'KEY',
  'LEU': 'LEU',
  'LNG': 'LNG',
  'MPC': 'MPC',
  'MTDR': 'MTDR',
  'NOG': 'NOG',
  'NOV': 'NOV',
  'OKE': 'OKE',
  'OVV': 'OVV',
  'OXY': 'OXY',
  'PAA': 'PAA',
  'PBF': 'PBF',
  'PPL': 'PPL',
  'PSX': 'PSX',
  'PTEN': 'PTEN',
  'RIG': 'RIG',
  'RRC': 'RRC',
  'SLB': 'SLB',
  'SM': 'SM',
  'TPL': 'TPL',
  'TRGP': 'TRGP',
  'UEC': 'UEC',
  'USAC': 'USAC',
  'VLO': 'VLO',
  'WES': 'WES',
  'WFRD': 'WFRD',
  'EXX.JO': 'EXX'},
 'Financiero': {'ADCB.AE': 'ADCB',
  'DFM.DU': 'DFM',
  'DIB.DU': 'DIB',
  'EMIRATESNBD.DU': 'EMIRATESNBD',
  'RAKBANK.AE': 'RAKBANK',
  'GGAL.BA': 'GGAL',
  'AFI.AX': 'AFI',
  'ARG.AX': 'ARG',
  'BOQ.AX': 'BOQ',
  'BPT.AX': 'BPT',
  'MQG.AX': 'MQG',
  'PNI.AX': 'PNI',
  'QBE.AX': 'QBE',
  'WBC.AX': 'WBC',
  'BBAS3.SA': 'BBAS3',
  'ITSA4.SA': 'ITSA4',
  'PSSA3.SA': 'PSSA3',
  'BNS.TO': 'BNS',
  'CM.TO': 'CM',
  'EQB.TO': 'EQB',
  'L.TO': 'L',
  'ONEX.TO': 'ONEX',
  'POW.TO': 'POW',
  'SLF.TO': 'SLF',
  'U-UN.TO': 'U.UN',
  'ALLN.SW': 'ALLN',
  'BCGE.SW': 'BCGE',
  'BEKN.SW': 'BEKN',
  'CFR.SW': 'CFR',
  'CMBN.SW': 'CMBN',
  'GRKP.SW': 'GRKP',
  'PGHN.SW': 'PGHN',
  'SLHN.SW': 'SLHN',
  'SPSN.SW': 'SPSN',
  'UBSG.SW': 'UBSG',
  'VAHN.SW': 'VAHN',
  'ZUGN.SW': 'ZUGER',
  '000166.SZ': '000166',
  '000563.SZ': '000563',
  '000686.SZ': '000686',
  '000750.SZ': '000750',
  '000783.SZ': '000783',
  '000987.SZ': '000987',
  '001227.SZ': '001227',
  '002244.SZ': '002244',
  '002797.SZ': '002797',
  '002945.SZ': '002945',
  '300059.SZ': '300059',
  '600015.SS': '600015',
  '600016.SS': '600016',
  '600036.SS': '600036',
  '600095.SS': '600095',
  '600606.SS': '600606',
  '600906.SS': '600906',
  '600928.SS': '600928',
  '601059.SS': '601059',
  '601099.SS': '601099',
  '601128.SS': '601128',
  '601166.SS': '601166',
  '601211.SS': '601211',
  '601229.SS': '601229',
  '601318.SS': '601318',
  '601336.SS': '601336',
  '601519.SS': '601519',
  '601555.SS': '601555',
  '601601.SS': '601601',
  '601688.SS': '601688',
  '601696.SS': '601696',
  '601818.SS': '601818',
  '601838.SS': '601838',
  'CIBEST.CO': 'CIBEST',
  'GRUPOSURA.CO': 'GRUPOSURA',
  'ALMB.CO': 'ALMB',
  'JYSK.CO': 'JYSK',
  'RILBA.CO': 'RILBA',
  'SPNO.CO': 'SPNO',
  'A5G.F': 'A5G',
  'ALV.DE': 'ALV',
  'BAMI.MI': 'BAMI',
  'BCP.LS': 'BCP',
  'BIRG.IR': 'BIRG',
  'BN.PA': 'BN',
  'BNP.PA': 'BNP',
  'BPE.MI': 'BPE',
  'BREB.DE': 'BREB',
  'CAF.MC': 'CAF',
  'CBK.DE': 'CBK',
  'COFA.PA': 'COFA',
  'DWNI.DE': 'DWNI',
  'EBS.VI': 'EBS',
  'ETE.AT': 'ETE',
  'EXO.MI': 'EXO',
  'GYC.DE': 'GYC',
  'HB.CY': 'HB',
  'LEG.DE': 'LEG',
  'MAP.MC': 'MAP',
  'MB.MI': 'MB',
  'MC.PA': 'MC',
  'OBS.PA': 'OBS',
  'RBI.VI': 'RBI',
  'SAB.MC': 'SAB',
  'SAMPO.HE': 'SAMPO',
  'SDF.DE': 'SDF',
  'SOF.BR': 'SOF',
  'TPEIR.AT': 'TPEIR',
  'UCB.BR': 'UCB',
  'ZABA.ZG': 'ZABA',
  'ALW.L': 'ALW',
  'ATT.L': 'ATT',
  'BARC.L': 'BARC',
  'CNA.L': 'CNA',
  'EMG.L': 'EMG',
  'FCIT.L': 'FCIT',
  'HICL.L': 'HICL',
  'ICP.L': 'ICG',
  'IWG.L': 'IWG',
  'JGGI.L': 'JGGI',
  'MNKS.L': 'MNKS',
  'PNL.L': 'PNL',
  'RAT.L': 'RAT',
  'RCP.L': 'RCP',
  'UTG.L': 'UTG',
  '0010.HK': '10',
  '0011.HK': '11',
  '1109.HK': '1109',
  '0123.HK': '123',
  '1299.HK': '1299',
  '1375.HK': '1375',
  '0023.HK': '23',
  '2328.HK': '2328',
  '3328.HK': '3328',
  '3618.HK': '3618',
  '0683.HK': '683',
  '6881.HK': '6881',
  '0083.HK': '83',
  '0939.HK': '939',
  'MOL.BU': 'MOL',
  'BBCA.JK': 'BBCA',
  'ALHE.TA': 'ALHE',
  'CLIS.TA': 'CLIS',
  'FIBI.TA': 'FIBI',
  'LUMI.TA': 'LUMI',
  'MMHD.TA': 'MMHD',
  'PEL.BO': '500302',
  'BAJAJHLDNG.BO': '500490',
  'SREINFRA.BO': '511218',
  'PSB.BO': '533295',
  'BAJAJFINSV.NS': 'BAJAJFINSV',
  'BANKBARODA.NS': 'BANKBARODA',
  'CANBK.NS': 'CANBK',
  'CENTRALBK.NS': 'CENTRALBK',
  'DLF.NS': 'DLF',
  'FEDERALBNK.NS': 'FEDERALBNK',
  'HDFCBANK.NS': 'HDFCBANK',
  'ICICIBANK.NS': 'ICICIBANK',
  'IDBI.NS': 'IDBI',
  'INDIANB.NS': 'INDIANB',
  'INDUSINDBK.NS': 'INDUSINDBK',
  'KARURVYSYA.NS': 'KARURVYSYA',
  'LICHSGFIN.NS': 'LICHSGFIN',
  'M&MFIN.NS': 'M&MFIN',
  'MFSL.NS': 'MFSL',
  'MOTILALOFS.NS': 'MOTILALOFS',
  'OBEROIRLTY.NS': 'OBEROIRLTY',
  'PFC.NS': 'PFC',
  'PNB.NS': 'PNB',
  'UCOBANK.NS': 'UCOBANK',
  '1878.T': '1878',
  '2801.T': '2801',
  '3289.T': '3289',
  '8304.T': '8304',
  '8308.T': '8308',
  '8316.T': '8316',
  '8354.T': '8354',
  '8411.T': '8411',
  '8421.T': '8421',
  '8591.T': '8591',
  '8750.T': '8750',
  '8802.T': '8802',
  '016360.KS': 'A016360',
  '029780.KS': 'A029780',
  '032830.KS': 'A032830',
  '039490.KS': 'A039490',
  '086790.KS': 'A086790',
  'ABK.KW': 'ABK',
  'BOUBYAN.KW': 'BOUBYAN',
  'BURG.KW': 'BURG',
  'KFH.KW': 'KFH',
  'MABANEE.KW': 'MABANEE',
  'ELEKTRA.MX': 'ELEKTRA _',
  'Q.MX': 'Q _',
  'AMBANK.KL': 'AMBANK',
  'PBBANK.KL': 'PBBANK',
  'MING.OL': 'MING',
  'OLT.OL': 'OLT',
  'NONG.OL': 'SB1NO',
  'BBVAC1.LM': 'BBVAC1',
  'CREDITC1.LM': 'CREDITC1',
  'ALI.PS': 'ALI',
  'BPI.PS': 'BPI',
  'SMPH.PS': 'SMPH',
  'KRU.WA': 'KRU',
  'PKO.WA': 'PKO',
  'SPL.WA': 'SPL',
  'TPE.WA': 'TPE',
  'BRES.QA': 'BRES',
  'ERES.QA': 'ERES',
  'MARK.QA': 'MARK',
  'QIBK.QA': 'QIBK',
  'QIIK.QA': 'QIIK',
  'TLV.RO': 'TLV',
  '1050.SR': '1050',
  '1060.SR': '1060',
  '1080.SR': '1080',
  '1150.SR': '1150',
  '4150.SR': '4150',
  'AZA.ST': 'AZA',
  'CAST.ST': 'CAST',
  'HUFV-A.ST': 'HUFV A',
  'INVE-A.ST': 'INVE A',
  'KINV-B.ST': 'KINV B',
  'LUND-B.ST': 'LUND B',
  'SAGA-A.ST': 'SAGA A',
  'BAY.BK': 'BAY',
  'BTS.BK': 'BTS',
  'SCB.BK': 'SCB',
  'TISCO.BK': 'TISCO',
  'AB': 'AB',
  'ABG': 'ABG',
  'ACGL': 'ACGL',
  'ADM': 'ADM',
  'AGM': 'AGM',
  'AGNC': 'AGNC',
  'AGO': 'AGO',
  'AIZ': 'AIZ',
  'AJG': 'AJG',
  'AMP': 'AMP',
  'APAM': 'APAM',
  'ARCC': 'ARCC',
  'ASB': 'ASB',
  'AUB': 'AUB',
  'AX': 'AX',
  'BAP': 'BAP',
  'BEN': 'BEN',
  'BKU': 'BKU',
  'BOH': 'BOH',
  'BRK-A': 'BRK.A',
  'BRO': 'BRO',
  'BXMT': 'BXMT',
  'CB': 'CB',
  'CBRE': 'CBRE',
  'CBU': 'CBU',
  'CME': 'CME',
  'CPAY': 'CPAY',
  'EFSC': 'EFSC',
  'EG': 'EG',
  'ENVA': 'ENVA',
  'EWBC': 'EWBC',
  'FCFS': 'FCFS',
  'FCNCA': 'FCNC.A',
  'FFBC': 'FFBC',
  'FHI': 'FHI',
  'FI': 'FI',
  'FNMA': 'FNMA',
  'GBDC': 'GBDC',
  'BRPHF': 'GLXY',
  'HAL': 'HAL',
  'HHH': 'HHH',
  'HTGC': 'HTGC',
  'IBKR': 'IBKR',
  'ICE': 'ICE',
  'IFS': 'IFS',
  'JEF': 'JEF',
  'JHG': 'JHG',
  'JKHY': 'JKHY',
  'JLL': 'JLL',
  'KMPR': 'KMPR',
  'LAZ': 'LAZ',
  'LPLA': 'LPLA',
  'MKL': 'MKL',
  'MORN': 'MORN',
  'MRC': 'MRC',
  'MS': 'MS',
  'NTRS': 'NTRS',
  'NWL': 'NWL',
  'PNFP': 'PNFP',
  'PPBI': 'PPBI',
  'PRI': 'PRI',
  'PRU': 'PRU',
  'PSA': 'PSA',
  'RDN': 'RDN',
  'RF': 'RF',
  'RGA': 'RGA',
  'RJF': 'RJF',
  'RLI': 'RLI',
  'RNR': 'RNR',
  'RNST': 'RNST',
  'SBCF': 'SBCF',
  'SCHW': 'SCHW',
  'SEIC': 'SEIC',
  'SFBS': 'SFBS',
  'SLM': 'SLM',
  'SSB': 'SSB',
  'STT': 'STT',
  'STWD': 'STWD',
  'TOWN': 'TOWN',
  'TRMK': 'TRMK',
  'UMBF': 'UMBF',
  'WAFD': 'WAFD',
  'WBS': 'WBS',
  'WD': 'WD',
  'WEX': 'WEX',
  'WSFS': 'WSFS',
  'WTFC': 'WTFC',
  'WTW': 'WTW',
  'ZG': 'ZG',
  'ACB.HM': 'ACB',
  'SHB.HM': 'SHB',
  'STB.HM': 'STB',
  'VCB.HM': 'VCB',
  'VIC.HM': 'VIC',
  'CPI.JO': 'CPI',
  'NED.JO': 'NED',
  'OMU.JO': 'OMU'},
 'Industria': {'CPU.AX': 'CPU',
  'HVN.AX': 'HVN',
  'QUB.AX': 'QUB',
  'SGH.AX': 'SGH',
  'SUN.AX': 'SUN',
  'WOR.AX': 'WOR',
  'MOTV3.SA': 'MOTV3',
  'ATRL.TO': 'ATRL',
  'ATS.TO': 'ATS',
  'BB.TO': 'BB',
  'CAE.TO': 'CAE',
  'FTT.TO': 'FTT',
  'ADEN.SW': 'ADEN',
  'BCHN.SW': 'BCHN',
  'BUCN.SW': 'BUCN',
  'DAE.SW': 'DAE',
  'DOKA.SW': 'DOKA',
  'FHZN.SW': 'FHZN',
  'SCHN.SW': 'SCHN',
  'ALLN.SW': 'ALLN',
  'BCGE.SW': 'BCGE',
  'BEKN.SW': 'BEKN',
  'CFR.SW': 'CFR',
  'CMBN.SW': 'CMBN',
  'GRKP.SW': 'GRKP',
  'PGHN.SW': 'PGHN',
  'SLHN.SW': 'SLHN',
  'SPSN.SW': 'SPSN',
  'UBSG.SW': 'UBSG',
  'VAHN.SW': 'VAHN',
  'ZUGER.SW': 'ZUGER',
  '000088.SZ': '000088',
  '000157.SZ': '000157',
  '000425.SZ': '000425',
  '000519.SZ': '000519',
  '000528.SZ': '000528',
  '000738.SZ': '000738',
  '000768.SZ': '000768',
  '000800.SZ': '000800',
  '002028.SZ': '002028',
  '002074.SZ': '002074',
  '002130.SZ': '002130',
  '002202.SZ': '002202',
  '002335.SZ': '002335',
  '002340.SZ': '002340',
  '002372.SZ': '002372',
  '002468.SZ': '002468',
  '002625.SZ': '002625',
  '002690.SZ': '002690',
  '300014.SZ': '300014',
  '300070.SZ': '300070',
  '300124.SZ': '300124',
  '300276.SZ': '300276',
  '600009.SS': '600009',
  '600039.SS': '600039',
  '600221.SS': '600221',
  '600233.SS': '600233',
  '600312.SS': '600312',
  '600320.SS': '600320',
  '600388.SS': '600388',
  '600416.SS': '600416',
  '600428.SS': '600428',
  '600435.SS': '600435',
  '600482.SS': '600482',
  '600516.SS': '600516',
  '600517.SS': '600517',
  '600522.SS': '600522',
  '600528.SS': '600528',
  '600577.SS': '600577',
  '600582.SS': '600582',
  '600720.SS': '600720',
  '600764.SS': '600764',
  '600862.SS': '600862',
  '600885.SS': '600885',
  '600893.SS': '600893',
  '601018.SS': '601018',
  '601106.SS': '601106',
  '601390.SS': '601390',
  '601668.SS': '601668',
  '603699.SS': '603699',
  'DSV.CO': 'DSV',
  'KBHL.CO': 'KBHL',
  'MAERSK-B.CO': 'MAERSK B',
  'SWDY.CA': 'SWDY',
  'AIR.PA': 'AIR',
  'ALO.PA': 'ALO',
  'ARCAD.AS': 'ARCAD',
  'BVI.PA': 'BVI',
  'FCC.MC': 'FCC',
  'FGR.PA': 'FGR',
  'FLU.VI': 'FLU',
  'G1A.DE': 'G1A',
  'GBF.DE': 'GBF',
  'GET.PA': 'GET',
  'HIAB.HE': 'HIAB',
  'HO.PA': 'HO',
  'JUN3.DE': 'JUN3',
  'KNEBV.HE': 'KNEBV',
  'KRX.IR': 'KRX',
  'LDO.MI': 'LDO',
  'LHA.DE': 'LHA',
  'LR.PA': 'LR',
  'MYTIL.AT': 'MTLN',
  'NDX1.DE': 'NDX1',
  'OSR.DE': 'OSR',
  'RHM.DE': 'RHM',
  'SCYR.MC': 'SCYR',
  'SGO.PA': 'SGO',
  'SIE.DE': 'SIE',
  'SIX2.DE': 'SIX2',
  'SU.PA': 'SU',
  'TEP.PA': 'TEP',
  'WKL.AS': 'WKL',
  'WRT1V.HE': 'WRT1V',
  'CHG.L': 'CHG',
  'DCC.L': 'DCC',
  'DPLM.L': 'DPLM',
  'EZJ.L': 'EZJ',
  'GFTU.L': 'GFTU',
  'IMI.L': 'IMI',
  'ITRK.L': 'ITRK',
  'MTO.L': 'MTO',
  'SPX.L': 'SPX',
  '0001.HK': '1',
  '1055.HK': '1055',
  '1199.HK': '1199',
  '1308.HK': '1308',
  '2331.HK': '2331',
  '2866.HK': '2866',
  '0317.HK': '317',
  '3898.HK': '3898',
  '0525.HK': '525',
  '0053.HK': '53',
  '0552.HK': '552',
  '0753.HK': '753',
  '500002.BO': '500002',
  '500008.BO': '500008',
  '500048.BO': '500048',
  '500480.BO': '500480',
  '512599.BO': '512599',
  '522113.BO': '522113',
  '523395.BO': '523395',
  '533655.BO': '533655',
  '534309.BO': '534309',
  'AIAENG.NS': 'AIAENG',
  'CGPOWER.NS': 'CGPOWER',
  'GMRINFRA.NS': 'GMRAIRPORT',
  'KEC.NS': 'KEC',
  'SIEMENS.NS': 'SIEMENS',
  'SUZLON.NS': 'SUZLON',
  'TECHNOE.NS': 'TECHNOE',
  'THERMAX.NS': 'THERMAX',
  '1812.T': '1812',
  '1944.T': '1944',
  '2768.T': '2768',
  '3064.T': '3064',
  '4666.T': '4666',
  '5201.T': '5201',
  '5333.T': '5333',
  '5393.T': '5393',
  '6141.T': '6141',
  '6201.T': '6201',
  '6273.T': '6273',
  '6302.T': '6302',
  '6481.T': '6481',
  '6503.T': '6503',
  '6504.T': '6504',
  '6506.T': '6506',
  '6594.T': '6594',
  '7911.T': '7911',
  '7912.T': '7912',
  '8002.T': '8002',
  '8012.T': '8012',
  '9020.T': '9020',
  '9021.T': '9021',
  '9064.T': '9064',
  '9072.T': '9072',
  '9107.T': '9107',
  '9201.T': '9201',
  '9435.T': '9435',
  '000880.KS': 'A000880',
  '001440.KS': 'A001440',
  '003550.KS': 'A003550',
  '006260.KS': 'A006260',
  '010140.KS': 'A010140',
  '010620.KS': 'A010620',
  '012450.KS': 'A012450',
  '034020.KS': 'A034020',
  '086520.KQ': 'A086520',
  '272210.KS': 'A272210',
  'ASURB.MX': 'ASUR B',
  'GAPB.MX': 'GAP B',
  'OMAB.MX': 'OMA B',
  'GAMUDA.KL': 'GAMUDA',
  'IJM.KL': 'IJM',
  'AKER.OL': 'AKER',
  'VEI.OL': 'VEI',
  'AIA.NZ': 'AIA',
  'JGS.PS': 'JGS',
  'ASSA-B.ST': 'ASSA B',
  'INDT.ST': 'INDT',
  'LOOMIS.ST': 'LOOMIS',
  'NIBE-B.ST': 'NIBE B',
  '5E2.SI': '5E2',
  'C07.SI': 'C07',
  'C52.SI': 'C52',
  'C6L.SI': 'C6L',
  'S58.SI': 'S58',
  'S63.SI': 'S63',
  'BEM.BK': 'BEM',
  'THYAO.IS': 'THYAO',
  'AAL': 'AAL',
  'AAON': 'AAON',
  'ADP': 'ADP',
  'AIT': 'AIT',
  'ALK': 'ALK',
  'AME': 'AME',
  'AYI': 'AYI',
  'AZZ': 'AZZ',
  'BAH': 'BAH',
  'BDX': 'BDX',
  'BYD': 'BYD',
  'CACI': 'CACI',
  'CAT': 'CAT',
  'CBZ': 'CBZ',
  'CHRW': 'CHRW',
  'CMI': 'CMI',
  'CSL': 'CSL',
  'CWST': 'CWST',
  'DAL': 'DAL',
  'DAN': 'DAN',
  'DE': 'DE',
  'DG': 'DG',
  'EMR': 'EMR',
  'ESE': 'ESE',
  'EXLS': 'EXLS',
  'EXPO': 'EXPO',
  'FA': 'FA',

In [433]:
data

,Date,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,statement currency,ticker,sector,year
0,2005-06-30 00:00:00+00:00,0.119474,0.228549,0.322841,0.229128,,,,,"2,75x",1.085531,-5.505000e+08,ZAR,WHL,ConsumoDiscrecional,2005
1,2006-06-30 00:00:00+00:00,0.105058,0.211413,0.348945,0.211801,,,,,"1,88x",0.814459,-6.673000e+08,ZAR,WHL,ConsumoDiscrecional,2006
2,2007-06-30 00:00:00+00:00,0.111854,0.196765,0.368874,0.198564,0.343962,0.127572,0.061829,0.062537,"1,76x",1.22021,-4.246442e-02,ZAR,WHL,ConsumoDiscrecional,2007
3,2008-06-30 00:00:00+00:00,0.086335,0.190569,0.276615,0.191861,0.312317,0.099687,0.046684,0.047107,"0,94x",0.687608,-9.917817e-03,ZAR,WHL,ConsumoDiscrecional,2008
4,2009-06-30 00:00:00+00:00,0.127596,0.250081,0.381028,0.276762,0.338518,0.113493,0.056929,0.057477,"1,68x",0.511405,1.126722e-02,ZAR,WHL,ConsumoDiscrecional,2009
5,2010-06-30 00:00:00+00:00,0.145308,0.260569,0.391839,0.289163,0.332322,0.100543,0.053777,0.054204,"1,28x",0.457892,3.355705e-02,ZAR,WHL,ConsumoDiscrecional,2010
6,2011-06-30 00:00:00+00:00,0.18047,0.322293,0.440573,0.3401,0.347862,0.093425,0.063756,0.063756,"1,41x",0.245758,3.228833e-02,ZAR,WHL,ConsumoDiscrecional,2011
7,2012-06-30 00:00:00+00:00,0.210097,0.379487,0.473833,0.396759,0.356069,0.122815,0.07027,0.071598,"1,18x",0.221626,3.083485e-02,ZAR,WHL,ConsumoDiscrecional,2012
8,2013-06-30 00:00:00+00:00,0.22764,0.409914,0.500592,0.425462,0.384733,0.126891,0.071962,0.073722,"1,23x",0.233369,2.077952e-02,ZAR,WHL,ConsumoDiscrecional,2013
9,2014-06-30 00:00:00+00:00,0.16158,0.245462,0.453546,0.261091,0.390309,0.128743,0.070139,0.072733,"1,05x",1.400211,1.372554e-02,ZAR,WHL,ConsumoDiscrecional,2014
10,2015-06-30 00:00:00+00:00,0.096942,0.175711,0.298467,0.175711,0.409691,0.13188,0.055145,0.055145,"0,91x",1.212336,3.220897e-03,ZAR,WHL,ConsumoDiscrecional,2015
11,2016-06-30 00:00:00+00:00,0.094042,0.149323,0.254952,0.150276,0.405913,0.139868,0.066827,0.066827,"0,94x",0.923888,1.262999e-02,ZAR,WHL,ConsumoDiscrecional,2016
12,2017-06-30 00:00:00+00:00,0.11422,0.175934,0.280259,0.185685,0.396964,0.147596,0.081054,0.085177,"0,97x",0.809907,-9.168031e-03,ZAR,WHL,ConsumoDiscrecional,2017
13,2018-06-30 00:00:00+00:00,-0.083392,-0.087977,-0.220833,0.070817,0.392057,0.010322,-0.051755,0.020956,"0,96x",1.211088,-2.070212e-03,ZAR,WHL,ConsumoDiscrecional,2018
14,2019-06-30 00:00:00+00:00,-0.02855,-0.016325,-0.096358,0.121071,0.382529,0.01926,-0.014856,0.035814,"1,12x",1.713407,-6.087301e-03,ZAR,WHL,ConsumoDiscrecional,2019
15,2020-06-30 00:00:00+00:00,0.01103,0.062931,0.069988,0.07887,0.351055,0.122729,0.007714,0.015681,"1,01x",7.045616,5.374751e-02,ZAR,WHL,ConsumoDiscrecional,2020
16,2021-06-30 00:00:00+00:00,0.068974,0.12828,0.526909,0.117501,0.36752,0.157282,0.052829,0.045453,"1,04x",3.63611,8.384648e-02,ZAR,WHL,ConsumoDiscrecional,2021
17,2022-06-30 00:00:00+00:00,0.066537,0.103902,0.352467,0.097559,0.355329,0.16069,0.056837,0.051957,"1,12x",2.707431,7.409504e-02,ZAR,WHL,ConsumoDiscrecional,2022
18,2023-06-30 00:00:00+00:00,0.106478,0.165522,0.426997,0.136774,0.371212,0.145186,0.070213,0.054343,"1,02x",1.421566,3.684997e-02,ZAR,WHL,ConsumoDiscrecional,2023
19,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,1.019168e-03,ZAR,WHL,ConsumoDiscrecional,2024

In [ ]:
# import json
# dest_path = "C:/TFM/tfm_env/data/02_intermediate/02.2.2 EmparejamientoTickerExchange/"

# # Guardar en archivo JSON
# with open(dest_path + "tiker_consumo_discrecional2.json", "w", encoding="utf-8") as f:
#     json.dump(new_discretional_tickers, f, indent=4, ensure_ascii=False)

In [153]:
data.head()

,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,ticker,sector
30/6/05,0.119474,0.228549,0.322841,0.229128,,,,,"2,75x",1.085531,-5.505000e+08,WHL,ConsumoDiscrecional
30/6/06,0.105058,0.211413,0.348945,0.211801,,,,,"1,88x",0.814459,-6.673000e+08,WHL,ConsumoDiscrecional
30/6/07,0.111854,0.196765,0.368874,0.198564,0.343962,0.127572,0.061829,0.062537,"1,76x",1.22021,-4.246442e-02,WHL,ConsumoDiscrecional
30/6/08,0.086335,0.190569,0.276615,0.191861,0.312317,0.099687,0.046684,0.047107,"0,94x",0.687608,-9.917817e-03,WHL,ConsumoDiscrecional
30/6/09,0.127596,0.250081,0.381028,0.276762,0.338518,0.113493,0.056929,0.057477,"1,68x",0.511405,1.126722e-02,WHL,ConsumoDiscrecional

In [ ]:
selected_data_dir_dest

for file in os.listdir(selected_data_dir_dest):
    d = pd.read_csv(selected_data_dir_dest + file, index_col="id")
    break

d

,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,ticker,sector
id,,,,,,,,,,,,,
31/12/05,0.027828,0.055699,0.081928,0.058309,0.182241,0.173516,0.046169,0.046169,"1,21x",1.073635,-0.052447,559,ConsumoDiscrecional
31/12/06,0.035960,0.069599,0.108246,0.077537,0.192040,0.166307,0.050959,0.055599,"0,95x",0.851650,0.040267,559,ConsumoDiscrecional
31/12/07,0.049382,0.086620,0.146612,0.091243,0.203532,0.167756,0.062186,0.065505,"0,91x",0.542055,0.017622,559,ConsumoDiscrecional
31/12/08,0.039087,0.066865,0.133089,0.073904,0.169688,0.131086,0.045544,0.050338,"0,78x",1.551826,-0.002920,559,ConsumoDiscrecional
31/12/09,0.045809,0.079689,0.171058,0.092497,0.181175,0.129816,0.047772,0.055450,"0,81x",0.781977,0.099250,559,ConsumoDiscrecional
31/12/10,0.061320,0.131180,0.157621,0.148380,0.176660,0.116431,0.054453,0.060367,"1,35x",0.215893,0.012263,559,ConsumoDiscrecional
31/12/11,0.055250,0.112830,0.123628,0.127275,0.178075,0.115621,0.057743,0.062475,"1,27x",0.164551,-0.028843,559,ConsumoDiscrecional
31/12/12,0.049255,0.114153,0.113270,0.131144,0.172927,0.127724,0.052273,0.056596,"1,75x",0.461065,0.036181,559,ConsumoDiscrecional
31/12/13,0.055343,0.112539,0.139677,0.132235,0.197785,0.131003,0.057289,0.064612,"1,38x",0.617321,0.101476,559,ConsumoDiscrecional
31/12/14,0.065307,0.151083,0.190177,0.179210,0.222041,0.146429,0.071912,0.084760,"1,35x",0.454127,0.084709,559,ConsumoDiscrecional
31/12/15,0.062904,0.156837,0.188464,0.185472,0.212654,0.145136,0.076029,0.088123,"1,44x",0.376630,0.075960,559,ConsumoDiscrecional
31/12/16,0.068423,0.159569,0.193169,0.187399,0.219471,0.146080,0.077306,0.088052,"1,20x",0.350003,0.063457,559,ConsumoDiscrecional
31/12/17,0.076497,0.157306,0.187561,0.175735,0.206660,0.137199,0.079029,0.085812,"1,32x",0.191249,0.062990,559,ConsumoDiscrecional
31/12/18,0.061295,0.123286,0.140804,0.139350,0.185972,0.119363,0.063597,0.070733,"1,40x",0.322992,-0.041613,559,ConsumoDiscrecional
31/12/19,0.044527,0.086643,0.102941,0.107761,0.175717,0.109475,0.050659,0.062364,"1,41x",0.321474,0.072006,559,ConsumoDiscrecional
31/12/20,0.031629,0.055060,0.063178,0.083560,0.162369,0.098022,0.040079,0.059530,"1,82x",0.178174,0.084291,559,ConsumoDiscrecional
31/12/21,0.042415,0.063248,0.080010,0.086886,0.133056,0.095340,0.047932,0.057426,"1,96x",0.282717,0.054124,559,ConsumoDiscrecional
31/12/22,0.044937,0.070428,0.093797,0.090496,0.132434,0.106405,0.057729,0.064885,"1,31x",0.405666,0.059843,559,ConsumoDiscrecional
31/12/23,0.040995,0.067297,0.093588,0.086503,0.148649,0.110747,0.056708,0.066015,"1,17x",0.534109,0.057155,559,ConsumoDiscrecional
31/12/24,0.044042,0.071510,0.105611,0.096725,0.178789,0.133225,0.073902,0.090874,"1,33x",0.578750,0.072651,559,ConsumoDiscrecional

In [437]:
d = pd.read_csv("data/02_intermediate/02.2.1 SeleccionHistoricoEstadosFinancierosUnificado/AllDataClosePrices.csv", index_col="Date")
# d.index = pd.to_datetime(d.index)
# d[d.index.year == 2024]

C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\2792004605.py:1: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  d = pd.read_csv("data/02_intermediate/02.2.1 SeleccionHistoricoEstadosFinancierosUnificado/AllDataClosePrices.csv", index_col="Date")

In [438]:
d[d.ticker.notna()]

,Close,year,close currency,Date.1,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,Total Revenues,statement currency,ticker,sector
Date,,,,,,,,,,,,,,,,,,,
2004-01-01 00:00:00+00:00,1.150652,2004,AUD,2004-06-30 00:00:00+00:00,NaN,0.013959,NaN,0.015116,0.408122,0.097632,NaN,NaN,"3,06x",0.443614,0.029603,457.616,AUD,BRG,ConsumoDiscrecional
2004-01-02 00:00:00+00:00,1.141868,2004,AUD,2004-06-30 00:00:00+00:00,NaN,0.013959,NaN,0.015116,0.408122,0.097632,NaN,NaN,"3,06x",0.443614,0.029603,457.616,AUD,BRG,ConsumoDiscrecional
2004-01-05 00:00:00+00:00,1.124301,2004,AUD,2004-06-30 00:00:00+00:00,NaN,0.013959,NaN,0.015116,0.408122,0.097632,NaN,NaN,"3,06x",0.443614,0.029603,457.616,AUD,BRG,ConsumoDiscrecional
2004-01-06 00:00:00+00:00,1.141868,2004,AUD,2004-06-30 00:00:00+00:00,NaN,0.013959,NaN,0.015116,0.408122,0.097632,NaN,NaN,"3,06x",0.443614,0.029603,457.616,AUD,BRG,ConsumoDiscrecional
2004-01-07 00:00:00+00:00,1.124301,2004,AUD,2004-06-30 00:00:00+00:00,NaN,0.013959,NaN,0.015116,0.408122,0.097632,NaN,NaN,"3,06x",0.443614,0.029603,457.616,AUD,BRG,ConsumoDiscrecional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-23 00:00:00+00:00,6208.781250,2024,ZAc,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,0.001019,76533.000,ZAR,WHL,ConsumoDiscrecional
2024-12-24 00:00:00+00:00,6280.767090,2024,ZAc,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,0.001019,76533.000,ZAR,WHL,ConsumoDiscrecional
2024-12-27 00:00:00+00:00,6201.782715,2024,ZAc,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,0.001019,76533.000,ZAR,WHL,ConsumoDiscrecional
2024-12-30 00:00:00+00:00,6163.790039,2024,ZAc,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,0.001019,76533.000,ZAR,WHL,ConsumoDiscrecional
2024-12-31 00:00:00+00:00,6233.776367,2024,ZAc,2024-06-30 00:00:00+00:00,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92x",1.667526,0.001019,76533.000,ZAR,WHL,ConsumoDiscrecional

In [294]:
p = "data/01_raw/01.4 - DatosHistoricosPrecios/Empresas"

len(os.listdir(p))

226

In [292]:
d[d.ticker.notna()].ticker.nunique()

47

In [167]:
d["Current Ratio"] = d["Current Ratio"].apply(lambda x: str(x).replace("x", ""))

In [118]:
d.keys()

Index(['Return on Assets %', 'Return on Invested Capital %',
       'Return On Equity %', 'Normalized ROIC %', 'Gross Profit Margin %',
       'EBITDA Margin %', 'Net Income Margin %',
       'Normalized Net Income Margin %', 'Current Ratio',
       'Total Debt / Equity', '% Free Cash Flow Margins', 'ticker', 'sector'],
      dtype='object')

In [168]:
from sklearn.linear_model import LinearRegression
d1 = d.reset_index()

def to_ordinal(s):
    return pd.to_datetime(s).map(pd.Timestamp.toordinal).values.reshape(-1, 1)

def time_regress_impute_group(g: pd.DataFrame, cols, date_col="date"):
    g = g.copy()

    # 1) Asegurar fechas válidas
    g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
    if g[date_col].isna().all():
        return g  # sin fechas válidas no se puede ajustar
    X_all = g[date_col].map(pd.Timestamp.toordinal).to_numpy().reshape(-1, 1)

    for target in cols:
        # 2) Separar train / pred por disponibilidad del target
        mask_train = g[target].notna().to_numpy()
        mask_pred  = ~mask_train

        # Si no hay nada que imputar, saltar
        if mask_pred.sum() == 0:
            continue

        # 3) Filtrar filas de train que tengan X válido y target válido
        X_train = X_all[mask_train]
        y_train = g.loc[mask_train, target].to_numpy()

        # Necesitamos al menos 2 puntos para ajustar una recta
        if len(X_train) < 2:
            continue

        # 4) Ajustar y predecir solo si hay muestras a predecir
        model = LinearRegression()
        model.fit(X_train, y_train)

        X_pred = X_all[mask_pred]
        y_hat  = model.predict(X_pred)

        # 5) Escribir predicciones en las posiciones faltantes
        g.loc[g.index[mask_pred], target] = y_hat

    return g


columns = ['Return on Assets %', 'Return on Invested Capital %',
       'Return On Equity %', 'Normalized ROIC %', 'Gross Profit Margin %',
       'EBITDA Margin %', 'Net Income Margin %',
       'Normalized Net Income Margin %', 'Current Ratio',
       'Total Debt / Equity', '% Free Cash Flow Margins']


df = d1.groupby("ticker", group_keys=False).apply(time_regress_impute_group, cols=columns, date_col="id")

C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")
C:\Users\Edelmín\AppData\Local\Temp\ipykernel_18664\3076607675.py:11: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  g[date_col] = pd.to_datetime(g[date_col], errors="coerce")

In [169]:
df.isna().sum()

id                                0
Return on Assets %                0
Return on Invested Capital %      0
Return On Equity %                0
Normalized ROIC %                 0
Gross Profit Margin %             0
EBITDA Margin %                   0
Net Income Margin %               0
Normalized Net Income Margin %    0
Current Ratio                     0
Total Debt / Equity               0
% Free Cash Flow Margins          0
ticker                            0
sector                            0
dtype: int64

In [172]:
df

,id,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,ticker,sector
0,2004-06-30,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional
1,2005-06-30,0.046868,0.071712,0.083124,0.072656,0.421123,0.064129,0.029999,0.029999,"3,26",0.495526,-0.000862,BRG,ConsumoDiscrecional
2,2007-06-30,-0.123240,-0.143022,-0.290219,0.099171,0.359705,0.082380,-0.091546,0.045792,"1,56",0.806993,0.010370,BRG,ConsumoDiscrecional
3,2008-06-30,0.079251,0.126275,0.167958,0.129324,0.340271,0.089465,0.049098,0.049328,"1,93",0.407044,0.054535,BRG,ConsumoDiscrecional
4,2009-06-30,0.048150,0.089752,0.089392,0.091143,0.350291,0.065083,0.027214,0.027214,"2,13",0.299270,0.046564,BRG,ConsumoDiscrecional
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,2020-06-30,0.011030,0.062931,0.069988,0.078870,0.351055,0.122729,0.007714,0.015681,"1,01",7.045616,0.053748,WHL,ConsumoDiscrecional
3117,2021-06-30,0.068974,0.128280,0.526909,0.117501,0.367520,0.157282,0.052829,0.045453,"1,04",3.636110,0.083846,WHL,ConsumoDiscrecional
3118,2022-06-30,0.066537,0.103902,0.352467,0.097559,0.355329,0.160690,0.056837,0.051957,"1,12",2.707431,0.074095,WHL,ConsumoDiscrecional
3119,2023-06-30,0.106478,0.165522,0.426997,0.136774,0.371212,0.145186,0.070213,0.054343,"1,02",1.421566,0.036850,WHL,ConsumoDiscrecional
3120,2024-06-30,0.066548,0.127521,0.226909,0.140517,0.358917,0.112474,0.033881,0.037267,"0,92",1.667526,0.001019,WHL,ConsumoDiscrecional

In [187]:
new_discretional_tickers = {}

for key in discretional_tickers.keys():
    # print(key.split("_")[1])
    new_discretional_tickers[key.split("_")[1]] = discretional_tickers[key]

In [190]:
df["market_ticker"] = df["ticker"].apply(lambda ticker_name: new_discretional_tickers[ticker_name])

In [195]:
'000559.SZ_CNY.csv'.split("_")

['000559.SZ', 'CNY.csv']

In [203]:
ticker = new_discretional_tickers["BRG"]
historical_price_company_dir="data/01_raw/01.4 - DatosHistoricosPrecios/Empresas/"
hist_df =None
for file in os.listdir(historical_price_company_dir):
    if file.split("_")[0] == ticker:
        hist_df = pd.read_csv(f"{historical_price_company_dir}{file}", header=[0, 1, 2])
        break

In [258]:
df["id"] = df.id.apply(lambda x: pd.to_datetime(x, utc=True))
df["year"] = df.id.apply(lambda x: x.year)

In [262]:
df["id"] = df.id.apply(lambda x: pd.to_datetime(x, utc=True))
df["year"] = df.id.apply(lambda x: x.year)

C = hist_df["Close"].transpose().reset_index().transpose().iloc[2:]
C.rename(columns={0: "Close"}, inplace=True)
C["Date"] = hist_df["Price"]["Ticker"]["Date"]
C["Date"] = C.Date.apply(lambda x: pd.to_datetime(x, utc=True))
C["year"] = C.Date.apply(lambda x: x.year)

C = C.set_index("Date").join(df[df.ticker=="BRG"].set_index("year"), on="year", how="left", lsuffix="_", rsuffix="")
C

,Close,year,id,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,ticker,sector,market_ticker
Date,,,,,,,,,,,,,,,,,
1999-02-25 00:00:00+00:00,0.307016,1999,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-02-26 00:00:00+00:00,0.307016,1999,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-03-01 00:00:00+00:00,0.307016,1999,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-03-02 00:00:00+00:00,0.307016,1999,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-03-03 00:00:00+00:00,0.307016,1999,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-21 00:00:00+00:00,37.0,2025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08-22 00:00:00+00:00,35.130001,2025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08-25 00:00:00+00:00,34.59,2025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08-26 00:00:00+00:00,33.740002,2025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08-27 00:00:00+00:00,33.549999,2025,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [263]:
C[C.ticker.notna()]

,Close,year,id,Return on Assets %,Return on Invested Capital %,Return On Equity %,Normalized ROIC %,Gross Profit Margin %,EBITDA Margin %,Net Income Margin %,Normalized Net Income Margin %,Current Ratio,Total Debt / Equity,% Free Cash Flow Margins,ticker,sector,market_ticker
Date,,,,,,,,,,,,,,,,,
2004-01-01 00:00:00+00:00,1.150652,2004,2004-06-30 00:00:00+00:00,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional,BRG.AX
2004-01-02 00:00:00+00:00,1.141868,2004,2004-06-30 00:00:00+00:00,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional,BRG.AX
2004-01-05 00:00:00+00:00,1.124301,2004,2004-06-30 00:00:00+00:00,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional,BRG.AX
2004-01-06 00:00:00+00:00,1.141868,2004,2004-06-30 00:00:00+00:00,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional,BRG.AX
2004-01-07 00:00:00+00:00,1.124301,2004,2004-06-30 00:00:00+00:00,0.052282,0.013959,0.074506,0.015116,0.408122,0.097632,0.024784,0.052338,"3,06",0.443614,0.029603,BRG,ConsumoDiscrecional,BRG.AX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-23 00:00:00+00:00,35.838661,2024,2024-06-30 00:00:00+00:00,0.087268,0.126162,0.146497,0.127855,0.364013,0.159085,0.077456,0.077456,"2,26",0.183896,0.157188,BRG,ConsumoDiscrecional,BRG.AX
2024-12-24 00:00:00+00:00,35.321568,2024,2024-06-30 00:00:00+00:00,0.087268,0.126162,0.146497,0.127855,0.364013,0.159085,0.077456,0.077456,"2,26",0.183896,0.157188,BRG,ConsumoDiscrecional,BRG.AX
2024-12-27 00:00:00+00:00,36.017654,2024,2024-06-30 00:00:00+00:00,0.087268,0.126162,0.146497,0.127855,0.364013,0.159085,0.077456,0.077456,"2,26",0.183896,0.157188,BRG,ConsumoDiscrecional,BRG.AX
2024-12-30 00:00:00+00:00,35.78894,2024,2024-06-30 00:00:00+00:00,0.087268,0.126162,0.146497,0.127855,0.364013,0.159085,0.077456,0.077456,"2,26",0.183896,0.157188,BRG,ConsumoDiscrecional,BRG.AX
2024-12-31 00:00:00+00:00,35.18235,2024,2024-06-30 00:00:00+00:00,0.087268,0.126162,0.146497,0.127855,0.364013,0.159085,0.077456,0.077456,"2,26",0.183896,0.157188,BRG,ConsumoDiscrecional,BRG.AX

In [265]:
df.ticker.nunique()

159

In [320]:
len(set(d.ticker.unique()))

159

In [323]:
len(set(d.ticker.unique()).symmetric_difference(set(new_discretional_tickers.keys()))) + 159

226